<?php
define('ABSPATH',__DIR__.'/'); define('GDO_VERSION','1.2.0'); define('GDO_SCHEMA_VERSION',6);
$GLOBALS['user_exists']=true;$GLOBALS['scope_verified']=false;$GLOBALS['narrow']='';
function absint($v){return abs((int)$v);} function sanitize_key($v){return preg_replace('/[^a-z0-9_-]/','',strtolower((string)$v));} function wp_generate_uuid4(){return '123e4567-e89b-42d3-a456-426614174000';} function get_userdata($u){return $GLOBALS['user_exists']?(object)array('ID'=>7):false;} function wp_strip_all_tags($v){return strip_tags((string)$v);} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function apply_filters($h,$v){if($h==='gdo_cf01_practitioner_scope'&&$GLOBALS['scope_verified']){$v['restriction_status']='verified';$v['restrictions']=array();} if($h==='gdo_cf01_practitioner_result'&&$GLOBALS['narrow']){$v['result']=$GLOBALS['narrow'];$v['reason_code']='narrowed';} return $v;}
final class GDO_Membership_Adapter{public static $available=true,$subject=array(),$base=array(); public static function available(){return self::$available;} public static function membership_assertion($u,$a,$p,$j=''){return self::$subject;} public static function base_assertion($u){return self::$base;} public static function membership_allows($a){return is_array($a)&&isset($a['result'])&&sanitize_key($a['result'])==='allow';}}
final class GDO_API{public static $decision=array();public static function latest_decision($u){return self::$decision;}}
final class GDO_Application{public static $snapshot=array();public static function approved_snapshot($id){return self::$snapshot;}public static function fingerprint(array $p,array $e=array()){ksort($p);ksort($e);return hash('sha256',wp_json_encode(array('profile'=>$p,'evidence'=>$e),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}}
require dirname(__DIR__).'/includes/class-gdo-cf01-practitioner-contract.php';
$t=0;function ok($c,$m){global $t;++$t;if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo "PASS: $m\n";}
$uuid='123e4567-e89b-42d3-a456-426614174000';$future=gmdate('Y-m-d',time()+180*86400);$verified=gmdate('Y-m-d',time()+30*86400);
$subject=array('result'=>'allow','subject'=>array('platform_uuid'=>$uuid,'record_version'=>4),'membership'=>array('identity_assurance'=>'verified'));
$base=array('contract_version'=>'1.2.0','user_id'=>7,'membership_type'=>'doctor','status'=>'approved','approved'=>true,'suspended'=>false,'two_factor_ready'=>true,'phone_verified'=>true,'email_verified'=>true,'guardian_verified'=>false,'professional_verified'=>true,'eligible'=>true,'identity_documents_current'=>true);
$snapshot=array('schema'=>6,'application_uuid'=>$uuid,'application_version'=>2,'profile'=>array('country'=>'Pakistan','city'=>'Gujrat','qualification'=>'DHMS','licensing_authority'=>'NCH','specialty'=>'Classical Homeopathy','consultation_modes'=>'Online'),'evidence'=>array('identity'=>array('version'=>1,'content_hmac'=>str_repeat('b',64),'status'=>'accepted','validity_until'=>'','expires_at'=>''),'qualification'=>array('version'=>1,'content_hmac'=>str_repeat('c',64),'status'=>'accepted','validity_until'=>'','expires_at'=>''),'license'=>array('version'=>3,'content_hmac'=>str_repeat('d',64),'status'=>'accepted','validity_until'=>$future,'expires_at'=>'')),'verified_until'=>$verified);
$decision=array('application_id'=>9,'application_uuid'=>$uuid,'version'=>2,'row_version'=>11,'state'=>'verified','verified'=>true,'verified_until'=>$verified.' 23:59:59','fingerprint'=>GDO_Application::fingerprint($snapshot['profile'],$snapshot['evidence']),'checked_at'=>gmdate('c'));
GDO_Membership_Adapter::$subject=$subject;GDO_Membership_Adapter::$base=$base;GDO_API::$decision=$decision;GDO_Application::$snapshot=$snapshot;
$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'clinical_read','purpose'=>'patient_care'));ok($r['result']==='allow','current verified doctor allowed');ok($r['grants_clinical_authorization']===false,'eligibility does not grant clinical access');
$deny=$subject;$deny['result']='deny';GDO_Membership_Adapter::$subject=$deny;$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'clinical_read','purpose'=>'patient_care'));ok($r['result']==='unknown'&&$r['reason_code']==='file00_contract_invalid','File00 deny fails closed');GDO_Membership_Adapter::$subject=$subject;
$expired=$snapshot;$expired['evidence']['license']['expires_at']=gmdate('Y-m-d H:i:s',time()-60);$d=$decision;$d['fingerprint']=GDO_Application::fingerprint($expired['profile'],$expired['evidence']);GDO_Application::$snapshot=$expired;GDO_API::$decision=$d;$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'clinical_read','purpose'=>'patient_care'));ok($r['result']==='deny'&&$r['reason_code']==='professional_evidence_not_current','expired evidence review denies');GDO_Application::$snapshot=$snapshot;GDO_API::$decision=$decision;
$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'clinical_read','purpose'=>'patient_care','jurisdiction'=>'India'));ok($r['result']==='deny','jurisdiction mismatch denies');
$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'prescription_sign','purpose'=>'prescription','jurisdiction'=>'Pakistan'));ok($r['result']==='unknown','scope-sensitive action fails closed without structured restrictions');
$GLOBALS['scope_verified']=true;$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'prescription_sign','purpose'=>'prescription','jurisdiction'=>'Pakistan'));ok($r['result']==='allow','verified scope can admit bounded eligibility');
$GLOBALS['narrow']='deny';$r=GDO_CF01_Practitioner_Contract::assertion(7,array('action'=>'clinical_read','purpose'=>'patient_care'));ok($r['result']==='deny','monotonic extension may narrow allow');
echo "File 09 CF-01 practitioner runtime: {$t} PASS, 0 FAIL\n";
