from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
adv=t('includes/class-gdo-advanced-trust.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); priv=t('includes/class-gdo-privacy.php'); ops=t('includes/class-gdo-operations.php'); admin=t('includes/class-gdo-admin.php'); storage=t('includes/class-gdo-storage.php'); uninstall=t('uninstall.php'); trace=t('TRACEABILITY.md'); status=t('STATUS.md'); manifest=t('RELEASE-MANIFEST-1.3.0.md'); workflow=t('.github/workflows/file09-rc2-final.yml')
checks=[]
def c(n,topic,ok): checks.append((n,topic,bool(ok)))
# 01-20 trust registry/read uncertainty
c(1,'Runtime identity 1.3.0/schema 6',has(t('global-doctor-onboarding.php'),'Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )"))
c(2,'Status separates staging/live/operational',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
c(3,'Canonical owner/boundaries explicit',has(t('README.md'),'File 09 owns doctor applications','File 00: identity/membership/security assertions'))
c(4,'Issuer mutation requires runtime gate',has(adv,'register_issuer( array $data )','GDO_Operations::mutation_allowed()','gdo_issuer_runtime_not_ready'))
c(5,'Issuer duplicate query DB uncertainty fails closed','gdo_issuer_duplicate_query' in adv)
c(6,'Issuer review lookup DB uncertainty fails closed','gdo_issuer_review_query' in adv)
c(7,'Trusted issuer lookup distinguishes DB uncertainty','gdo_trusted_issuer_query' in adv)
c(8,'Jurisdiction rule lookup DB uncertainty fails closed','gdo_jurisdiction_rule_query' in hard)
c(9,'Credential check existence lookup DB uncertainty fails closed','gdo_trust_check_query' in adv)
c(10,'Authenticity reuse query DB uncertainty fails closed','gdo_authenticity_reuse_query' in adv)
c(11,'Fraud ring evidence-link query DB uncertainty fails closed','gdo_fraud_ring_query' in adv)
c(12,'Fraud ring duplicate-signal query DB uncertainty fails closed','gdo_fraud_ring_signal_query' in adv)
c(13,'Risk explanation DB uncertainty returns error','gdo_risk_explanation_query' in adv)
c(14,'Conflict duplicate query DB uncertainty fails closed','gdo_conflict_query' in adv)
c(15,'Reviewer calibration DB uncertainty returns error','gdo_reviewer_calibration_query' in adv)
c(16,'Public history DB uncertainty explicit','gdo_public_history_query' in adv)
c(17,'Active passport lookup DB uncertainty explicit','gdo_active_passport_query' in adv)
c(18,'Public passport lookup DB uncertainty explicit','gdo_passport_lookup_query' in hard)
c(19,'Passport token lookup DB uncertainty explicit','gdo_passport_token_query' in adv)
c(20,'Command-center trust-check query DB uncertainty explicit','gdo_command_center_query' in adv)
# 21-45 resumable upload/durability
c(21,'Upload session start uses runtime mutation gate','gdo_upload_runtime_not_ready' in adv)
c(22,'Upload session transaction start checked','gdo_upload_transaction' in adv)
c(23,'Aggregate application lock query DB error checked','gdo_upload_application_lock' in adv)
c(24,'Locked target application read DB error checked','gdo_upload_application_query' in adv)
c(25,'Temporary aggregate quota query DB uncertainty checked','gdo_upload_temp_quota_unknown' in adv)
c(26,'Temp-file chmod/permission persistence checked','gdo_upload_temp_permissions' in adv)
c(27,'Upload session insert and COMMIT checked',has(adv,'gdo_upload_session_store',"false===$wpdb->query('COMMIT')"))
c(28,'Chunk append uses runtime mutation gate','gdo_upload_chunk_runtime_not_ready' in adv)
c(29,'Chunk transaction start checked','gdo_upload_chunk_transaction' in adv)
c(30,'Chunk row-lock query DB uncertainty checked','gdo_upload_chunk_query' in adv)
c(31,'Chunk seek result checked','gdo_upload_chunk_seek' in adv)
c(32,'Chunk fsync result checked','gdo_upload_chunk_sync' in adv)
c(33,'Chunk rollback truncation failure surfaced','gdo_upload_chunk_rollback_file' in adv)
c(34,'Chunk DB update/commit checked','gdo_upload_chunk_conflict' in adv)
c(35,'Finalize uses runtime mutation gate','gdo_upload_finalize_runtime_not_ready' in adv)
c(36,'Finalize transaction start checked','gdo_upload_finalize_transaction' in adv)
c(37,'Finalize row-lock DB uncertainty checked','gdo_upload_finalize_query' in adv)
c(38,'Finalize recovery-state persistence checked','gdo_upload_finalize_state_store' in adv)
c(39,'Finalize hash_file failure explicit','gdo_upload_hash_read' in adv)
c(40,'Finalize filesize failure explicit','gdo_upload_size_read' in adv)
c(41,'Finalize stage_upload errors preserved','if(is_wp_error($result))' in adv or 'if ( is_wp_error( $result ) )' in adv)
c(42,'Finalize committed marker required','gdo_upload_commit_marker' in adv)
c(43,'Committed temp-file deletion failure surfaced','gdo_upload_temp_delete' in adv)
c(44,'Post-finalize authenticity failure audited','doctor_upload_authenticity_postcheck_failed' in adv)
c(45,'Post-finalize AI-assist failure audited','doctor_upload_ai_postcheck_failed' in adv)
# 46-65 privacy/public/API/lifecycle
c(46,'Base cleanup DB uncertainty explicit','gdo_upload_cleanup_query' in adv)
c(47,'Advanced privacy export can return WP_Error on DB uncertainty','gdo_privacy_export_query' in adv)
c(48,'WordPress exporter handles Advanced Trust export error','gdo_advanced_export_failed' in priv)
c(49,'Transparency aggregate queries reject DB uncertainty','gdo_transparency_query' in adv)
c(50,'Public transparency propagates degraded/error state','is_wp_error($snapshot)' in adv or 'is_wp_error( $snapshot )' in adv)
c(51,'Issuer REST path uses runtime mutation gate',has(adv,'rest_issuer','gdo_issuer_runtime_not_ready'))
c(52,'Issuer-review REST path uses runtime mutation gate','gdo_issuer_review_runtime_not_ready' in adv)
c(53,'Upload chunk/finalize methods are not login-only mutation paths',has(adv,'gdo_upload_chunk_runtime_not_ready','gdo_upload_finalize_runtime_not_ready'))
c(54,'Viewing-room grant requires runtime readiness','gdo_viewing_room_runtime_not_ready' in adv)
c(55,'Hardening reverification lookup/store DB uncertainty checked',has(hard,'gdo_reverification_query','gdo_reverification_store'))
c(56,'Submission equivalency existence DB uncertainty checked','gdo_submission_equivalency_query' in hard)
c(57,'Submission equivalency failure audited','doctor_submission_equivalency_failed' in hard)
c(58,'Submission fraud scan failure audited','doctor_submission_fraud_scan_failed' in hard)
c(59,'Submission schedule failure audited','doctor_submission_reverification_schedule_failed' in hard)
c(60,'history_once lookup DB uncertainty checked','gdo_history_query' in hard)
c(61,'history_once add failure surfaced/audited','doctor_professional_history_store_failed' in hard)
c(62,'Decision passport revoke failure audited','doctor_verification_passport_revoke_failed' in hard)
c(63,'Decision reverification schedule failure audited','doctor_decision_reverification_schedule_failed' in hard)
start=hard.index('public static function ensure_passport')
ensure=hard[start:start+900]
c(64,'ensure_passport fails on uncertain active-passport lookup',has(ensure,'active_passport_for_application','is_wp_error($existing)') or has(ensure,'active_passport_for_application','is_wp_error( $existing )'))
c(65,'Hardening public passport DB lookup uncertainty checked','gdo_passport_lookup_query' in hard)
# 66-80 storage/privacy/prior gates/release
c(66,'Hardened expired-upload cleanup verifies storage health','gdo_upload_cleanup_storage' in hard)
c(67,'Advanced privacy erasure verifies storage health before physical proof','gdo_privacy_storage_unavailable' in hard)
c(68,'Hardened cleanup checks DB state write','gdo_upload_cleanup_store' in hard)
c(69,'Advanced privacy erasure checks operational DB cleanup','gdo_privacy_operational_cleanup' in hard)
c(70,'Public projection excludes cure/clinical authorization',has(hard,"'cure_guarantee'=>false","'clinical_authorization'=>false"))
c(71,'Provider result payload minimization/bounds remain',has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
c(72,'AI/provider never finalizes professional decision',has(adv,'automated_decision_forbidden','human_final_decision_required'))
c(73,'Ordinary manager mutations obey Safe Mode',has(admin,'mutation_allowed','File 09 mutations are unavailable until Safe Mode is cleared'))
c(74,'Private storage canonical path/symlink controls remain',has(storage,'realpath','is_link','gdo_storage_permissions','gdo_storage_temp_permissions','gdo_storage_final_permissions'))
c(75,'Core and Advanced schema runtime gates remain',has(ops,"get_option( 'gdo_schema_version'","get_option( 'gdo_advanced_trust_schema'"))
c(76,'Destructive uninstall remains triple authorized',has(uninstall,'SABRI_ALLOW_DESTRUCTIVE_UNINSTALL','gdo_allow_destructive_uninstall','gdo_destructive_uninstall_confirmation','hash_equals'))
c(77,'Privacy legal hold remains fail closed',has(priv,'legal_hold','Erasure is paused because legal-hold status could not be verified safely.'))
c(78,'All 17 FR identifiers traceable',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)))
c(79,'All 10 NFR and 24 AT identifiers traceable',all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)) and all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
lock=json.loads(t('RELEASE-LOCK.json')); release_files=[x for x in t('RELEASE-FILES.txt').splitlines() if x.strip()]
c(80,'Sixth fresh historical ledger/gate evidence remains preserved',(root/'REVIEW-80-ROUNDS-RC6-R6.md').exists() and lock.get('sixth_review_baseline')=='6fa0a5cb7063b6b821bd50c105c735470f589b80' and lock.get('sixth_review_rounds')==80 and lock.get('sixth_defect_rounds')==60 and lock.get('sixth_clean_rounds')==20 and 'REVIEW-80-ROUNDS-RC6-R6.md' in release_files and 'python3 tests/eighty-round-audit-r6.py' in workflow and '**57-entry**' in manifest)
failed=[x for x in checks if not x[2]]
for n,topic,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {topic}')
print(f'File 09 RC6 sixth fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
print('Defect-bearing rounds: 04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,28,29,30,31,32,33,35,36,37,38,39,40,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,80')
print('Clean rounds: 01,02,03,25,27,34,41,42,68,69,70,71,72,73,74,75,76,77,78,79')
if failed: raise SystemExit(1)
