from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
main=t('global-doctor-onboarding.php'); evidence=t('includes/class-gdo-evidence.php'); app=t('includes/class-gdo-application.php'); admin=t('includes/class-gdo-admin.php'); notify=t('includes/class-gdo-notifications.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); adv=t('includes/class-gdo-advanced-trust.php'); member=t('includes/class-gdo-membership-adapter.php'); ops=t('includes/class-gdo-operations.php'); privacy=t('includes/class-gdo-privacy.php'); retention=t('includes/class-gdo-retention.php'); storage=t('includes/class-gdo-storage.php'); migration=t('includes/class-gdo-migration.php'); claims=t('includes/class-gdo-claims.php'); state=t('includes/class-gdo-state.php'); integ=t('includes/class-gdo-integration-contracts.php'); trace=t('TRACEABILITY.md'); status=t('STATUS.md'); manifest=t('RELEASE-MANIFEST-1.3.0.md'); readme=t('README.md'); workflow=t('.github/workflows/file09-rc2-final.yml'); release_files=[x for x in t('RELEASE-FILES.txt').splitlines() if x.strip()]; lock=json.loads(t('RELEASE-LOCK.json'))
checks=[]
def c(n,topic,ok): checks.append((n,topic,bool(ok)))
# R01-R03 — frozen-baseline and governing-domain sanity.
c(1,'Canonical File09 runtime/schema identity remains stable',has(main,'Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )"))
c(2,'Repository truth still separates staging/live/operational',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
c(3,'Latest central/File09/Advanced-Trust trace remains explicit',has(trace,'F09-CEN-01','F09-CEN-02','F09-AT-24'))
# R04-R13 — defects discovered on frozen R8 baseline 75ea54ed... and corrected in R9.
c(4,'Evidence review reauthorizes current reviewer capability and step-up at owner-command boundary',has(evidence,'gdo_evidence_review_forbidden',"$reviewer_id !== get_current_user_id()","GDO_Membership_Adapter::can( 'sabri_verify_doctors', $reviewer_id )",'GDO_Membership_Adapter::recent_step_up( $reviewer_id )'))
c(5,'Evidence/application DB uncertainty during review is fail-visible',has(evidence,'gdo_evidence_review_query','gdo_evidence_review_application_query',"$wpdb->last_error = ''"))
c(6,'Credential-grant consumption rechecks download capability and DB reads at use time',has(evidence,'gdo_evidence_grant_query','gdo_evidence_grant_evidence_query','gdo_evidence_grant_application_query',"$download_authorized = 'download' !== sanitize_key( $expected_mode )","sabri_access_doctor_credentials"))
c(7,'Idempotent submission proves COMMIT success before returning success',has(app,'gdo_submit_idempotent_commit',"false === $wpdb->query( 'COMMIT' )"))
c(8,'Appeal workflow UI distinguishes DB read failure from no open appeal',has(admin,'Appeal workflow state is temporarily unavailable because the database read failed','No appeal action has been assumed'))
c(9,'Bounded outbox replay surfaces processing failure instead of redirecting false success',has(admin,"$result = GDO_Notifications::process( 100 )",'is_wp_error( $result )',"'response'=>503"))
c(10,'Dead-letter replay reauthorizes current manager and recent step-up at method boundary',has(notify,'gdo_outbox_replay_forbidden',"$actor_id !== get_current_user_id()","sabri_manage_doctor_verification",'recent_step_up( $actor_id )'))
c(11,'Continuous monitoring uses an exclusive processing lease with stale-lease recovery',has(hard,"monitor_status='processing'",'processing_lease_expired','gdo_trust_monitor_claim_failed','release_monitor_claim','doctor_continuous_verification_monitor_superseded'))
c(12,'Advanced Trust privacy erasure uses an atomic DB transaction and verified COMMIT',has(hard,'gdo_privacy_advanced_transaction',"$wpdb->query('START TRANSACTION')",'gdo_privacy_advanced_commit',"$wpdb->query('ROLLBACK')"))
c(13,'Historical ninth-review metadata remains preserved after later release evolution',has(manifest,'Ninth fresh 80-round') and (root/'REVIEW-80-ROUNDS-RC6-R9.md').exists() and lock.get('ninth_review_baseline')=='75ea54ed5113bf7ee16e90443f17cc1b941933a9' and lock.get('ninth_review_rounds')==80 and lock.get('ninth_defect_rounds')==10 and lock.get('ninth_clean_rounds')==70)
# R14-R80 — fresh post-correction adversarial/control pass.
c(14,'Evidence review remains assigned-case and scope bound',has(evidence,'assigned_reviewer_id','reviewer_scope_allows','reviewer_case_allows'))
c(15,'Evidence accepted license still requires verified registry result and future validity',has(evidence,'gdo_license_review',"'verified','active','matched'",'validity_until'))
c(16,'Evidence access grant remains one-time/session-bound',has(evidence,'session_digest','used_at','gdo_evidence_grant_conflict'))
c(17,'Credential review bytes are purpose-watermarked and PDF requires provider',has(evidence,'PRIVATE REVIEW','gdo_watermark_pdf_bytes','gdo_pdf_watermark_provider'))
c(18,'Encrypted private storage health is rechecked before reads/deletes',has(storage,'public static function read','public static function delete_verified','self::health()'))
c(19,'Private storage remains outside public upload tree and rejects unsafe paths',has(storage,'outside the public uploads directory','realpath','symlink'))
c(20,'Application state transitions remain explicit and optimistic-concurrency guarded',has(state,'FOR UPDATE','row_version','can_transition'))
c(21,'Submission remains snapshot/idempotency bound',has(app,'submission_hash','GDO_Evidence::records_checked( $app->id, true )','hash_equals( (string) $app->submission_hash, $submission_hash )','gdo_submit_state'))
c(22,'Applicant edits remain ownership/state constrained',has(app,'save_draft','user_id','draft','more_information'))
c(23,'Core migration future-schema state remains fail-closed',has(migration,'gdo_schema_future_version','$current > GDO_SCHEMA_VERSION'))
c(24,'Core migration lock/idempotency remains present',has(migration,'gdo_schema_migration_lock','gdo_migration_lock'))
c(25,'Advanced Trust future schema remains fail-closed',has(hard,'gdo_advanced_schema_future_version','$current_schema > self::SCHEMA_VERSION'))
c(26,'Advanced Trust physical schema/index postconditions remain verified',has(hard,'SHOW INDEX FROM','gdo_advanced_schema_index_read','gdo_advanced_schema_index'))
c(27,'Continuous-monitor schema/runtime readiness remains fail-visible',has(hard,'doctor_continuous_verification_runtime_failed','gdo_trust_monitor_runtime_not_ready'))
c(28,'Continuous monitor still treats provider errors as degraded facts, not decisions',has(hard,'$provider_failure = true','degraded','gdo_continuous_verification_adverse_result'))
c(29,'Continuous monitoring does not silently auto-revoke professional status','gdo_continuous_verification_adverse_result' in hard and 'GDO_State::transition' not in hard[hard.index('public static function continuous_monitor'):hard.index('public static function cleanup_upload_sessions')] and 'GDO_Claims::issue' not in hard[hard.index('public static function continuous_monitor'):hard.index('public static function cleanup_upload_sessions')])
c(30,'Event-driven reverification uses distinct bounded wakeup scheduling',has(hard,'gdo_trust_reverification_wakeup','wp_schedule_single_event','schedule_wakeup'))
c(31,'Passport lookup rechecks current membership and professional verification',has(hard,'verify_passport_uuid','identity_assurance_current','public_verified'))
c(32,'Public passport response is non-cacheable after use-time recheck',has(hard,"Cache-Control', 'no-store, max-age=0, must-revalidate'","Pragma', 'no-cache'"))
c(33,'Passport public projection carries no cure or clinical-authorization grant',has(hard,"'cure_guarantee'=>false","'clinical_authorization'=>false"))
c(34,'Passport issue remains serialized/versioned',has(hard,'SELECT MAX(version)','FOR UPDATE','gdo_passport_store'))
c(35,'Jurisdiction rules remain draft-first with independent approval',has(hard,'gdo_jurisdiction_rule_separation','created_by','approved_by'))
c(36,'Approved jurisdiction-rule versions remain immutable',has(hard,'gdo_jurisdiction_rule_immutable','create a new version'))
c(37,'Issuer registry/review remain runtime and privileged-step-up gated',has(adv,'gdo_issuer_runtime_not_ready','gdo_issuer_review_runtime_not_ready','current privileged step-up'))
c(38,'External provider payloads remain minimized and bounded',has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
c(39,'External provider secrets/tokens are filtered from persisted result arrays',has(adv,'secret|password|token|api[_-]?key|private[_-]?key|credential'))
c(40,'AI/equivalency/translation remain assistance/fact paths, not final decision owners',has(adv,'ai_assistance','equivalency_assessment','translation_assistance') and 'reviewer-assistance adapters only' in adv)
c(41,'Reviewer conflict declaration remains explicit and auditable',has(adv,'declare_conflict','doctor_reviewer_conflict_declared','reason_hash'))
c(42,'Reviewer conflict query uncertainty remains deny-by-default',has(adv,'gdo_conflict_query','fail-closed conflict'))
c(43,'Conflict resolution remains privileged and step-up controlled',has(adv,'resolve_conflict','Conflict resolution requires privileged authorization and step-up'))
c(44,'Dual-review requirement remains human/monotonic',has(adv,'requires_dual_review','gdo_requires_dual_review'))
c(45,'Reviewer routing remains bounded and conflict-aware',has(adv,'smart_reviewer_candidates','has_conflict'))
c(46,'Calibration remains aggregate and bounded',has(adv,'reviewer_calibration','agreement_rate','overturn_rate'))
c(47,'Risk explanation remains human-review-required',has(adv,'risk_explanation','human_review_required','opaque_rejection_forbidden'))
c(48,'Risk mutation remains Safe-Mode/runtime gated',has(t('includes/class-gdo-risk.php'),'gdo_risk_runtime_not_ready','mutation_allowed'))
c(49,'Risk resolution reauthorizes current actor',has(t('includes/class-gdo-risk.php'),'gdo_risk_resolution_forbidden','get_current_user_id','recent_step_up'))
c(50,'Notification producer remains File19 sun.event.v1 with minimized presentation',has(notify,'sun.event.v1','Never forward the raw event payload'))
c(51,'Notification outbox remains retry/dead-letter capable',has(notify,'doctor_verification_outbox_dead_letter',"'status'=>$terminal ? 'dead' : 'failed'","'available_at'=>gmdate",'$attempts'))
c(52,'Outbox delivery/failure persistence remains mandatory',has(notify,'gdo_outbox_delivery_persist_failed','gdo_outbox_failure_persist_failed'))
c(53,'File09 does not directly deliver wp_mail', 'wp_mail(' not in notify)
c(54,'Professional decision claims remain signed and version-bound',has(claims,'GDO_CLAIM_SIGNING_KEY','claim_version','signature'))
c(55,'File00 claim consumption still requires explicit acceptance',has(notify,'did not explicitly accept the claim','gdo_claim_provider_unavailable'))
c(56,'File00 current identity assurance remains required for privileged capabilities',has(member,'identity_assurance_current','self::sanctioned','self::base_assertion'))
c(57,'File02 recent step-up remains session/current-user bound',has(member,'recent_step_up','$user_id !== get_current_user_id()','SA_Professional_Reauthentication::assertion'))
c(58,'Reviewer scope remains File00 capability and reviewer-profile constrained',has(member,'reviewer_scope_allows',"self::can( 'sabri_verify_doctors'",'reviewer_profiles'))
c(59,'Reviewer private-evidence access remains active-case bound',has(member,'reviewer_case_allows','assigned_reviewer_id','appeal_pending'))
c(60,'Safe Mode blocks ordinary mutations',has(ops,'mutation_allowed','safe_mode'))
c(61,'Repair reauthorizes current management actor and step-up',has(ops,'gdo_repair_forbidden','get_current_user_id','recent_step_up'))
c(62,'Safe Mode change reauthorizes current management actor and step-up',has(ops,'gdo_safe_mode_forbidden','get_current_user_id','recent_step_up'))
c(63,'Operational health includes schema/storage/scheduler/dependency evidence',has(ops,'core_schema','advanced_trust_schema','storage','retention_cron','outbox_cron','trust_monitor_cron'))
c(64,'Operational reconciliation is bounded and failure-visible',has(ops,'public static function reconcile','gdo_reconcile','LIMIT'))
c(65,'Privacy export remains paginated/minimized and failure-aware',has(privacy,'public function export( $email, $page = 1 )','$per = 20','LIMIT %d OFFSET %d',"'done'=>false"))
c(66,'Native privacy erasure invokes Advanced Trust erasure',has(privacy,'privacy_erase_application','GDO_Advanced_Trust_Hardening'))
c(67,'Legal hold remains an erasure blocker',has(privacy,'legal_hold','erasure'))
c(68,'Retention refuses unsafe active professional states',has(retention,"array( 'verified','reinstated','under_review','recommended','appeal_pending','submitted','resubmitted','renewal_due' )",'continue;'))
c(69,'Retention propagates maintenance failure rather than false completion',has(retention,'retention_failure','doctor_verification_retention_failed'))
c(70,'Resumable upload cleanup remains hardened and failure-visible',has(hard,'cleanup_upload_sessions','gdo_upload_cleanup_unsafe_path'))
c(71,'Canonical File20 shell integration remains adapter-only',has(integ,'gdo.file09.owner-contract','sabri_shell_page_contracts'))
c(72,'File03/07/08/21/23/26 consume public-safe verification projections',has(integ,'gdo.file03.doctor-profile-eligibility','gdo.file07.directory-eligibility','gdo.file08.clinic-eligibility','gdo.file21.publishing-eligibility','gdo.file23.publishing-dashboard-eligibility','gdo.file26.doctor-verification-projection'))
c(73,'File26 projection excludes private evidence and donor/rank advantage',has(integ,"'evidence_exposed'","'donor_rank_advantage'","'private_indexing' => false"))
c(74,'File19 notification metadata contract remains explicit',has(integ,'gdo.file19.notification-event','sun.event.v1'))
c(75,'Release docs continue to require external Hostinger staging',has(status,'Hostinger') and has(manifest,'Staging') and 'false' in status.lower())
c(76,'Rollback/migration operational document remains present and nontrivial',len(t('MIGRATION-ROLLBACK-1.3.0.md'))>1000)
c(77,'Security/privacy operational guidance remains present and nontrivial',len(t('SECURITY-PRIVACY.md'))>1000)
c(78,'All FR/NFR/Advanced-Trust identifiers remain traceable',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)) and all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)) and all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
c(79,'Eight prior 80-round ledgers remain preserved as historical evidence',all((root/x).exists() for x in ['REVIEW-80-ROUNDS-RC6.md','REVIEW-80-ROUNDS-RC6-R2.md','REVIEW-80-ROUNDS-RC6-R3.md','REVIEW-80-ROUNDS-RC6-R4.md','REVIEW-80-ROUNDS-RC6-R5.md','REVIEW-80-ROUNDS-RC6-R6.md','REVIEW-80-ROUNDS-RC6-R7.md','REVIEW-80-ROUNDS-RC6-R8.md']))
c(80,'Ninth fresh historical ledger/gate/release-lock evidence remains preserved',(root/'REVIEW-80-ROUNDS-RC6-R9.md').exists() and lock.get('ninth_review_baseline')=='75ea54ed5113bf7ee16e90443f17cc1b941933a9' and lock.get('ninth_review_rounds')==80 and lock.get('ninth_defect_rounds')==10 and lock.get('ninth_clean_rounds')==70 and 'tests/eighty-round-audit-r9.py' in workflow)
failed=[x for x in checks if not x[2]]
for n,topic,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {topic}')
print(f'File 09 RC6 ninth fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
defects={4,5,6,7,8,9,10,11,12,13}
print('Defect-bearing rounds: ' + ','.join(f'{i:02d}' for i in sorted(defects)))
print('Clean rounds: ' + ','.join(f'{i:02d}' for i in range(1,81) if i not in defects))
if failed: raise SystemExit(1)
