from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
main=t('global-doctor-onboarding.php'); migration=t('includes/class-gdo-migration.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); adv=t('includes/class-gdo-advanced-trust.php'); plugin=t('includes/class-gdo-plugin.php'); act=t('includes/class-gdo-activator.php'); ops=t('includes/class-gdo-operations.php'); storage=t('includes/class-gdo-storage.php'); crypto=t('includes/class-gdo-crypto.php'); admin=t('includes/class-gdo-admin.php'); uninstall=t('uninstall.php'); evidence=t('includes/class-gdo-evidence.php'); privacy=t('includes/class-gdo-privacy.php'); retention=t('includes/class-gdo-retention.php'); notify=t('includes/class-gdo-notifications.php'); claims=t('includes/class-gdo-claims.php'); state=t('includes/class-gdo-state.php'); member=t('includes/class-gdo-membership-adapter.php'); risk=t('includes/class-gdo-risk.php'); trace=t('TRACEABILITY.md'); status=t('STATUS.md'); manifest=t('RELEASE-MANIFEST-1.3.0.md'); workflow=t('.github/workflows/file09-rc2-final.yml')
checks=[]
def c(n,topic,ok): checks.append((n,topic,bool(ok)))
c(1,'Canonical runtime remains 1.3.0/schema 6',has(main,'Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )"))
c(2,'Status truth still separates repository/staging/live/operational',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
c(3,'Latest plan trace and canonical owner remain present',has(trace,'F09-CEN-01','F09-CEN-02','F09-AT-24'))
c(4,'Future core schema is rejected fail-closed',has(migration,'gdo_schema_future_version','$current > GDO_SCHEMA_VERSION','$current === GDO_SCHEMA_VERSION'))
c(5,'Base Advanced Trust physical-schema verification remains forward-compatible within hardening ownership',has(adv,'verify_installation','self::SCHEMA_VERSION'))
c(6,'Future Advanced Trust schema is rejected by hardening maximum gate',has(hard,'gdo_advanced_schema_future_version','$current_schema > self::SCHEMA_VERSION'))
c(7,'Current schema physical postconditions remain enforced',has(t('includes/class-gdo-schema.php'),'SHOW COLUMNS FROM','SHOW TABLE STATUS LIKE','InnoDB'))
c(8,'Normal REST/integration hooks are registered only after migrations succeed',plugin.index('(new GDO_REST())->hooks();') > plugin.index('GDO_Advanced_Trust_Hardening::maybe_upgrade_schema()'))
c(9,'Jurisdiction REST mutation obeys runtime mutation gate',has(hard,'public static function rest_jurisdiction','GDO_Operations::mutation_allowed()','gdo_trust_runtime_not_ready'))
c(10,'Trust-check REST mutation obeys runtime mutation gate',hard[hard.index('public static function rest_check'):].find('GDO_Operations::mutation_allowed()') < 500)
c(11,'Continuous monitor propagates schema upgrade/runtime readiness errors',has(hard,'doctor_continuous_verification_runtime_failed','gdo_trust_monitor_runtime_not_ready'))
c(12,'Continuous monitor fails on monitor/evidence/application DB uncertainty',has(hard,'gdo_trust_monitor_query_failed','gdo_trust_monitor_application_query','gdo_trust_monitor_evidence_query'))
c(13,'Continuous monitor orphan deletion failure is surfaced',has(hard,'gdo_trust_monitor_orphan_delete',"'monitor_status'=>'processing'",'orphan_delete_failed'))
c(14,'Any primary-source WP_Error becomes provider degradation',has(hard,'if ( is_wp_error( $check ) )','$provider_failure = true;','continue;'))
c(15,'Continuous monitor persistence and cleanup failures propagate',has(hard,'gdo_trust_monitor_store_failed','$cleanup = self::cleanup_upload_sessions()','return $cleanup;'))
c(16,'Reverification wakeups use a distinct hook',has(hard,'gdo_trust_reverification_wakeup','wp_schedule_single_event'))
c(17,'Recurring jobs are validated by recurrence, not only next timestamp',has(act,'recurring_schedule_ready','wp_get_scheduled_event','self::recurring_schedule_ready( $hook, $recurrence )') and has(ops,'recurring_schedule_ready','wp_get_scheduled_event'))
c(18,'Managed page update failure is fatal during activation',has(act,'wp_update_post','File 09 could not update its managed application page safely'))
c(19,'Managed page metadata/map persistence is verified',has(act,'managed-page ownership metadata','managed page map'))
c(20,'Activation version/evidence option persistence is verified',has(act,'runtime version evidence could not be persisted','activation evidence could not be persisted'))
c(21,'Activation still requires File00/File02/key/storage readiness',has(act,'GDO_Membership_Adapter::available','authentication_available','GDO_Crypto::available','GDO_Storage::health'))
c(22,'Private storage uses canonical realpath boundary checks',has(storage,'realpath( $dir )','realpath( $uploads[\'basedir\'] )','canonical filesystem path'))
c(23,'Private storage is health-rechecked before reads',has(storage,'public static function read','self::health()'))
c(24,'Private storage is health-rechecked before verified deletion',storage[storage.index('public static function delete_verified'):].find('self::health()') < 250)
c(25,'Committed encrypted file hash is verified before success',has(storage,'gdo_storage_hash_failed','$sha256 = hash_file'))
c(26,'Active encryption key identifier is scalar/validated before indexing',has(crypto,'gdo_active_key_invalid','is_scalar','$ring[\'active\'] = $active'))
c(27,'AES-256-GCM envelope/authentication remains present',has(crypto,'aes-256-gcm','gdo_authentication_failure','GDO2'))
c(28,'Credential MIME/active-content/malware gates remain fail-closed',has(evidence,'FILEINFO_MIME_TYPE','EmbeddedFile','gdo_scan_required'))
c(29,'Evidence upload retains locked application/quota ownership checks',has(evidence,'FOR UPDATE','quota_allows','gdo_evidence_application_changed'))
c(30,'Rate limiter still fails closed on DB uncertainty',has(t('includes/class-gdo-rate-limiter.php'),'false === $ok','null === $raw_hits'))
c(31,'Expired resumable cleanup rejects symlink/non-file artifacts',has(hard,'gdo_upload_cleanup_unsafe_path','unsafe_chunk_path'))
c(32,'Privacy erasure pauses on unsafe resumable path',has(hard,'gdo_privacy_upload_unsafe_path','erasure is paused for operator review'))
c(33,'Manager capability no longer bypasses Safe Mode for ordinary mutations',has(admin,'private function guard( $capability, $allow_recovery = false )','! $allow_recovery && ! GDO_Operations::mutation_allowed()'))
c(34,'Ordinary admin writes use full runtime mutation readiness',has(admin,'File 09 mutations are unavailable until Safe Mode is cleared'))
c(35,'Safe-mode toggle/repair/outbox are explicit recovery exceptions only',admin.count("$this->guard( 'sabri_manage_doctor_verification', true );") == 3)
c(36,'Assignment remains nonce/capability/row-version controlled',has(admin,'gdo_assign_application','check_admin_referer','row_version'))
c(37,'Evidence review remains case-bound and step-up guarded',has(admin,'gdo_review_evidence','reviewer_case_allows'))
c(38,'Final decision retains transaction + independent reviewer + current evidence gates',has(admin,'gdo_finalize_decision','START TRANSACTION','recommender_id','GDO_Evidence::all_accepted'))
c(39,'Appeal assignment remains independent from prior reviewers',has(admin,'assign_appeal','recommender_id','finalizer_id'))
c(40,'Risk/quality management remains human and audited',has(admin,'resolve_risk','complete_quality_sample'))
c(41,'Destructive uninstall fails visibly on filesystem deletion uncertainty',has(uninstall,'private-storage file could not be removed','private-storage directory could not be removed','private-storage root could not be removed'))
c(42,'Destructive uninstall verifies table and option removal',has(uninstall,'SHOW TABLES LIKE','still exists after destructive uninstall','option could not be removed'))
c(43,'Destructive uninstall clears recurring monitor and wakeup hook',has(uninstall,'gdo_trust_continuous_monitor','gdo_trust_reverification_wakeup'))
c(44,'Default uninstall remains non-destructive without triple authorization',has(uninstall,'SABRI_ALLOW_DESTRUCTIVE_UNINSTALL','gdo_allow_destructive_uninstall','gdo_destructive_uninstall_confirmation','return;'))
c(45,'Privacy legal-hold/erasure controls remain present',has(privacy,'legal_hold','erasure'))
c(46,'Physical evidence deletion proof remains present',has(privacy,'delete_verified','deletion_proof'))
c(47,'Retention still fails closed when runtime is unavailable',has(retention,'gdo_retention_runtime_not_ready','mutation_allowed'))
c(48,'Retention still propagates each checked maintenance error',has(retention,'retention_failure','doctor_verification_retention_failed'))
c(49,'Renewal and expiry remain transactionally coupled to claim/outbox',has(retention,'GDO_Claims::issue','GDO_Notifications::queue','START TRANSACTION'))
c(50,'Professional claims remain signed and version bound',has(claims,'GDO_CLAIM_SIGNING_KEY','claim_version','signature'))
c(51,'Claim delivery still requires explicit File00 acceptance',has(notify,'did not explicitly accept the claim','gdo_claim_provider_unavailable'))
c(52,'File19 receives minimized presentation data only',has(notify,'Never forward the raw event payload','sun.event.v1'))
c(53,'Outbox delivery persistence remains mandatory',has(notify,'gdo_outbox_delivery_persist_failed','gdo_outbox_failure_persist_failed'))
c(54,'Application state transitions retain row lock/version checks',has(state,'FOR UPDATE','row_version'))
c(55,'File00 authority remains fail-closed',has(member,'FILE00_CONTRACT','valid_base_assertion'))
c(56,'Reviewer authority remains case bound',has(member,'reviewer_case_allows','reviewer_scope_allows'))
c(57,'Risk uncertainty remains fail-closed',has(risk,'gdo_risk_query_failed'))
c(58,'Public passport still rechecks current verified state',has(hard,'verify_passport_uuid','identity_assurance_current','public_verified'))
c(59,'Passport issue remains transaction/version serialized',has(hard,'SELECT MAX(version)','FOR UPDATE','gdo_passport_store'))
c(60,'Public passport contains no cure/clinical authorization grant',has(hard,"'cure_guarantee'=>false","'clinical_authorization'=>false"))
c(61,'Continuous monitoring still never silently auto-revokes', 'do_action( \'gdo_continuous_verification_adverse_result\'' in hard)
c(62,'Reviewer conflict uncertainty remains deny-by-default',has(adv,'has_conflict','fail-closed conflict'))
c(63,'Dual review remains monotonic/human controlled',has(adv,'requires_dual_review','gdo_requires_dual_review'))
c(64,'Provider payload minimization remains bounded',has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
c(65,'Private evidence grant remains one-time/session-bound',has(evidence,'session_digest','used_at','access_grants'))
c(66,'Evidence bytes never use public media URLs',has(storage,'outside the public uploads directory'))
c(67,'Operational schema repair includes Advanced Trust',has(ops,'GDO_Advanced_Trust_Hardening::maybe_upgrade_schema'))
c(68,'Operational health reports recurring monitor state',has(ops,"$checks['trust_monitor_cron']",'recurring_schedule_ready'))
c(69,'File20 shell remains adapter-only integration',has(plugin,'sabri_file20_navigation_items','sabri_file20_module_health'))
c(70,'Canonical integration contracts remain versioned', 'contract' in t('includes/class-gdo-integration-contracts.php').lower())
c(71,'Core schema table/column/InnoDB verification remains present',has(t('includes/class-gdo-schema.php'),'verify_installation','gdo_schema_engine_invalid'))
c(72,'Advanced Trust table/column/InnoDB verification remains present',has(adv,'gdo_advanced_schema_table','gdo_advanced_schema_engine'))
c(73,'Migration lock/idempotency remains present',has(migration,'gdo_schema_migration_lock','gdo_migration_lock'))
c(74,'Rollback documentation remains explicit', 'rollback' in t('MIGRATION-ROLLBACK-1.3.0.md').lower())
c(75,'Security/privacy guidance remains present',len(t('SECURITY-PRIVACY.md'))>500)
c(76,'Staging remains an external mandatory gate',has(t('STAGING-ACCEPTANCE.md'),'Staging') and 'false' in status.lower())
c(77,'All 17 FR identifiers remain traceable',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)))
c(78,'All 10 NFR and 24 AT identifiers remain traceable',all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)) and all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
c(79,'Four prior 80-round ledgers remain immutable historical evidence',all((root/x).exists() for x in ['REVIEW-80-ROUNDS-RC6.md','REVIEW-80-ROUNDS-RC6-R2.md','REVIEW-80-ROUNDS-RC6-R3.md','REVIEW-80-ROUNDS-RC6-R4.md']))
lock=json.loads(t('RELEASE-LOCK.json'))
c(80,'Fifth fresh ledger/gate/release lock/package count are synchronized',(root/'REVIEW-80-ROUNDS-RC6-R5.md').exists() and lock.get('fifth_review_rounds')==80 and lock.get('fifth_defect_rounds')==29 and lock.get('fifth_clean_rounds')==51 and lock.get('release_file_count')==len([x for x in t('RELEASE-FILES.txt').splitlines() if x.strip()]) and 'tests/eighty-round-audit-r5.py' in workflow and '56-entry' in manifest)
failed=[x for x in checks if not x[2]]
for n,topic,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {topic}')
print(f'File 09 RC6 fifth fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
print('Defect-bearing rounds: 04,06,08,09,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,31,32,33,34,35,41,42,43,80')
print('Clean rounds: ' + ','.join(f'{i:02d}' for i in range(1,81) if i not in {4,6,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,31,32,33,34,35,41,42,43,80}))
if failed: raise SystemExit(1)
