#!/usr/bin/env python3
from pathlib import Path
import re, sys

root=Path(__file__).resolve().parents[1]
def text(path): return (root/path).read_text(encoding='utf-8')
def has(s,*tokens): return all(t in s for t in tokens)
def check(n,topic,ok): checks.append((n,topic,bool(ok)))

main=text('global-doctor-onboarding.php')
app=text('includes/class-gdo-application.php')
audit=text('includes/class-gdo-audit.php')
claims=text('includes/class-gdo-claims.php')
state=text('includes/class-gdo-state.php')
member=text('includes/class-gdo-membership-adapter.php')
admin=text('includes/class-gdo-admin.php')
risk=text('includes/class-gdo-risk.php')
rate=text('includes/class-gdo-rate-limiter.php')
evidence=text('includes/class-gdo-evidence.php')
trust=text('includes/class-gdo-advanced-trust.php')
hard=text('includes/class-gdo-advanced-trust-hardening.php')
events=text('includes/class-gdo-advanced-trust-events.php')
notif=text('includes/class-gdo-notifications.php')
privacy=text('includes/class-gdo-privacy.php')
retention=text('includes/class-gdo-retention.php')
integ=text('includes/class-gdo-integration-contracts.php')
workflow=text('.github/workflows/file09-rc2-final.yml') if (root/'.github/workflows/file09-rc2-final.yml').exists() else ''
review=text('REVIEW-80-ROUNDS-RC6-R2.md')
status=text('STATUS.md')
manifest=text('RELEASE-MANIFEST-1.3.0.md')
migration=text('MIGRATION-ROLLBACK-1.3.0.md')
security=text('SECURITY-PRIVACY.md')
advanced=text('ADVANCED-TRUST-24.md')
checks=[]

check(1,'Canonical File09 ownership',has(integ,"'source_of_truth'          => 'file09'","'direct_table_meta_write'=> false"))
check(2,'Truth status separation',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
check(3,'RC6 identity and fresh-second review status',has(status,'RC6') and 'fresh second 80-round' in status.lower())
check(4,'Bootstrap trust/hardening/event order',main.index('class-gdo-advanced-trust.php') < main.index('class-gdo-advanced-trust-hardening.php') < main.index('class-gdo-advanced-trust-events.php'))
check(5,'File00 hard dependency',has(text('includes/class-gdo-plugin.php'),'File 00 Membership Core is required','GDO_Membership_Adapter::available'))
check(6,'File02 recent step-up',has(member,'SA_Professional_Reauthentication::assertion','recent_step_up'))
check(7,'Eligibility policy and professional age gate',has(text('includes/class-gdo-policy.php'),'eligibility','gdo_minimum_professional_age','professional_age_not_met'))
check(8,'Consent ledger lock/no REPLACE',has(app,'SELECT * FROM ' + "' . GDO_Schema::table( 'applications' ) . '" if False else 'FOR UPDATE','active_consent') and 'REPLACE INTO' not in app)
check(9,'Completeness rejects expired evidence',has(app,"strtotime( $record->expires_at . ' UTC' ) <= time()"))
check(10,'Draft save optimistic concurrency',has(app,'row_version=row_version+1','gdo_concurrent_change'))
check(11,'Submission snapshot/evidence evaluated under application lock',has(app,"SELECT * FROM ' . GDO_Schema::table( 'applications' ) . ' WHERE id=%d AND user_id=%d FOR UPDATE",'submission_hash','GDO_Risk::evaluate'))
check(12,'Resubmitted immutability/state law',"array( 'draft','more_information' )" in app and 'resubmitted' in state)
check(13,'Audit chain read failure is fail-closed',has(audit,'gdo_audit_chain_read_failed','$wpdb->last_error'))
check(14,'Transition facts publish only after commit',has(audit,'publish_transition') and 'GDO_Membership_Adapter::audit' not in audit[audit.index('function transition'):audit.index('function publish_transition')])
check(15,'Claim signing, subject/version binding and safe transaction start',has(claims,'hash_hmac','claim_version','subject_uuid','membership_record_version','gdo_claim_transaction'))
check(16,'Claim external publish separated from transaction',has(claims,'function publish','if ( $manage_transaction )') and 'GDO_Membership_Adapter::audit' not in claims[claims.index('function issue'):claims.index('function publish')])
check(17,'Reviewer scope is monotonic',has(member,'reviewer_scope_allows','return $allowed && $filtered'))
check(18,'Private evidence is case-bound, not merely scope-bound',has(member,'reviewer_case_allows') and evidence.count('reviewer_case_allows') >= 2)
check(19,'Self-review blocked',has(evidence,'absint( $app->user_id ) === $reviewer_id'))
check(20,'Reviewer workload DB uncertainty fails closed',has(admin,'gdo_reviewer_workload_unknown','$open_apps','$open_appeals'))
check(21,'Appeal-reopened review can be independently reassigned',has(admin,'review_reassigned',"'under_review' === $app->state && empty( $app->assigned_reviewer_id )"))
check(22,'Recommendation revalidates locked application',has(admin,'lock_application( $id )','GDO_Risk::unresolved','verification_recommended'))
check(23,'Finalization revalidates locked application',has(admin,"'recommended' !== $app->state",'verification_finalized','refresh_approved_snapshot') or has(admin,"'recommended' !== $app->state",'verification_finalized'))
check(24,'Lifecycle and appeal resolution lock current state',admin.count('lock_application( $id )') >= 4 and 'FOR UPDATE' in admin)
check(25,'Approved snapshot integrity is checked',has(app,'stored_approved_snapshot','approved_fingerprint'))
check(26,'Risk detection query/store failures propagate',has(risk,'gdo_risk_query_failed','gdo_risk_store_failed'))
check(27,'Unresolved-risk query uncertainty narrows decision',has(risk,'return true','gdo_risk_query_failed') or '$wpdb->last_error' in risk)
check(28,'Rate limiter read/write failures fail closed',has(rate,'null === $raw_hits','$wpdb->last_error','return false'))
check(29,'Professional claim acknowledgement gate retained',has(claims,'acknowledge','accepted'))
check(30,'Legacy File19 transport requires explicit acknowledgement',has(notif,'gdo_legacy_notification_ack_supported','gdo_legacy_notification_acknowledged'))
check(31,'Evidence upload locks current editable application',has(evidence,'locked_app',"FOR UPDATE",'is_active_doctor_candidate'))
check(32,'Persistent evidence quota DB error fails closed',has(evidence,'raw_used','quota_allows','$wpdb->last_error'))
check(33,'Evidence upload audit is post-commit/outer-transaction safe',has(evidence,'if ( $manage_transaction )','doctor_evidence_uploaded'))
check(34,'Resumable sessions enforce aggregate temp quota',has(trust,'gdo_resumable_temp_quota_bytes','expected_bytes','open\',\'finalizing') or has(trust,'gdo_resumable_temp_quota_bytes','expected_bytes'))
check(35,'Resumable quota uncertainty fails closed',has(trust,'gdo_upload_temp_quota_unknown','raw_reserved','$wpdb->last_error'))
check(36,'Chunk append serializes DB row and file lock',has(trust,'FOR UPDATE','LOCK_EX','gdo_upload_chunk_conflict'))
check(37,'Chunk order and exact size enforced',has(trust,'Upload chunks must arrive exactly once and in order','gdo_upload_chunk_size'))
check(38,'Finalize atomically claims open session',has(trust,"'state'=>'finalizing'",'gdo_upload_finalize_conflict'))
check(39,'Finalize marker failure is repair-observable',has(trust,'doctor_resumable_upload_commit_marker_failed','gdo_upload_commit_marker'))
check(40,'Resumable finalize uses canonical evidence path with explicit trusted internal provenance',has(trust,'GDO_Evidence::stage_upload','stage_upload($app,$row->document_type,$file,true,$path)') and has(evidence,'trusted_internal_path','native_uploaded && $filtered_uploaded'))
check(41,'Evidence grants recheck current case relation',has(evidence,'issue_view_grant','reviewer_case_allows','consume_view_grant'))
check(42,'Evidence grant one-time/session/step-up',has(evidence,'used_at','session_digest','recent_step_up'))
check(43,'Secure room no-download/watermark contract',has(trust,"'download_allowed'=>false",'watermark'))
check(44,'Primary-source unavailable path fails safe',has(trust,'provider_unavailable','trusted_issuer_not_available'))
check(45,'Provider request is re-allowlisted after extension filter',has(trust,'array_intersect_key','gdo_primary_source_request_minimized','issuer_context'))
check(46,'External references are token-safe/digested',has(trust,'safe_external_reference','refsha256:'))
check(47,'Equivalency cannot grant legal license',has(trust,'legal_license_grant'))
check(48,'Affiliation adapter gets minimized request, not raw app',"apply_filters('gdo_institutional_affiliation_verification',null,$request);" in trust)
check(49,'Translation adapter gets minimized payload, not raw evidence object',"apply_filters('gdo_credential_translation_assistance',null,$payload);" in trust)
check(50,'AI adapter minimized and final decision keys discarded',has(trust,"apply_filters('gdo_ai_evidence_assistance',null,$payload);","unset($result['decision'],$result['approve'],$result['reject']"))
check(51,'Conflict DB uncertainty fails closed',has(trust,'null===$raw_count','return true'))
check(52,'Conflict extension can only add conflict',has(trust,'return $detected || $filtered'))
check(53,'Dual review risk-query uncertainty fails closed',has(trust,'null===$raw_high','return true'))
check(54,'Smart routing skips DB-uncertain workload',has(trust,'raw_open','continue','null===$profiles'))
check(55,'Calibration excludes incomplete samples',has(trust,"'completed'!==sanitize_key($row['status'])",'agreement_rate'))
check(56,'Continuous monitoring does not mutate professional owner state','GDO_State::transition' not in hard[hard.index('function continuous_monitor'):hard.index('function cleanup_upload_sessions')])
check(57,'Degraded monitor retry/backoff retained',has(hard,"monitor_status IN ('scheduled','degraded')",'failure_count','wp_schedule_single_event'))
check(58,'Reverification uses explicit lifecycle facts',has(events,"'doctor_verification_transition'","'to_state'") and 'preg_match' not in events)
check(59,'Passport requires explicit future verification and intact snapshot',has(trust,'current_verification_expiry','stored_approved_snapshot','gdo_passport_not_eligible'))
check(60,'Passport transaction/version/supersession failures fail closed',has(trust,'gdo_passport_transaction','gdo_passport_version','gdo_passport_supersede'))
check(61,'Passport ensure verifies existing token before reuse',has(trust,'ensure_passport','verify_passport_uuid($existing->passport_uuid)'))
check(62,'Public passport rechecks underlying current truth',has(trust,'identity_assurance_current','stored_approved_snapshot','passport_issued<$snapshot_captured'))
verify=trust[trust.index('function verify_passport_uuid'):trust.index('function verify_passport_token')]
check(63,'Public passport read is read-only','revoke_passports_for_application' not in verify and '$wpdb->update' not in verify and '$wpdb->delete' not in verify)
check(64,'Public passport anti-cache/noarchive headers',has(events,'no-store, no-cache, must-revalidate','noarchive'))
check(65,'Renewal predecessor continuity retained',has(app,'verification_record_for_user','renewed_from_id') and 'renewal_due' in state)
check(66,'Scope badge has four-state semantics',all(x in trust for x in ['verified','pending','not_verified','not_applicable']))
check(67,'Public history is allowlisted',has(trust,'allowed_public','public_safe=$public_safe && in_array'))
check(68,'Public transparency fixed-window/cohort suppression',has(trust,'PUBLIC_WINDOW_DAYS','gdo_public_transparency_minimum_cohort',"'suppressed'=>true"))
check(69,'Advanced REST check is case-bound',hard.count('reviewer_case_allows') >= 1 and trust.count('reviewer_case_allows') >= 1)
check(70,'REST provider errors are structured',has(hard,"'ok'=>false",'rest_value'))
check(71,'Privacy export covers Advanced Trust',has(privacy,'privacy_export_rows','GDO_Advanced_Trust::privacy_export_rows'))
check(72,'Native privacy anonymization is transactionally grouped',has(privacy,'native database identity links were not partially committed','START TRANSACTION','FOR UPDATE'))
check(73,'Previously-deleted evidence must detach user identity or erasure stops',has(privacy,'previously deleted credential record could not be detached'))
check(74,'Advanced Trust privacy erasure is application-scoped and inventory-fail-closed',has(hard,'privacy_erase_application','gdo_privacy_upload_inventory'))
check(75,'Advanced Trust retention DB failures are observable',has(retention,'database_anonymization_failed','upload_inventory_failed'))
check(76,'Native retention child anonymization failures block completion',has(retention,'doctor_verification_retention_native_anonymize_failed','native_ok'))
check(77,'Orphan cleanup covers resumable chunks',has(retention,"0 === strpos( $name, '.chunk-' )"))
check(78,'Migration/rollback documents schema 2 and non-destructive rollback',('Advanced Trust schema: **2**' in migration or 'Advanced Trust schema `2`' in migration) and 'non-destructive' in migration.lower())
check(79,'Exact-head workflow executes fresh-second 80-round gate',has(workflow,'eighty-round-audit-r2.py','eighty-round-audit.py','advanced-trust-24.py'))
check(80,'Review/status/manifest synchronize fresh-second ledger',has(review,'Fresh Second Eighty-Round Re-Review','47 defect-bearing rounds','33 clean rounds') and 'fresh second 80-round' in status.lower() and 'fresh second 80-round' in manifest.lower())

if len(checks)!=80 or [n for n,_,_ in checks]!=list(range(1,81)):
    print('FAIL: control list incomplete',file=sys.stderr); sys.exit(1)
failed=[(n,t) for n,t,ok in checks if not ok]
if failed:
    for n,t in failed: print(f'FAIL R{n:02d}: {t}',file=sys.stderr)
    sys.exit(1)
DEFECT_ROUNDS=[3,8,9,11,13,14,15,16,18,20,21,22,23,24,26,27,28,30,31,32,33,34,35,38,41,45,46,48,49,50,51,52,53,54,59,60,61,62,63,65,69,72,73,75,76,79,80]
CLEAN_ROUNDS=[n for n in range(1,81) if n not in DEFECT_ROUNDS]
assert len(DEFECT_ROUNDS)==47 and len(CLEAN_ROUNDS)==33
print('File 09 RC6 fresh-second eighty-round audit: 80 PASS, 0 FAIL')
print('Defect-bearing rounds:',','.join(f'{n:02d}' for n in DEFECT_ROUNDS))
print('Clean rounds:',','.join(f'{n:02d}' for n in CLEAN_ROUNDS))
