from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
main=t('global-doctor-onboarding.php'); app=t('includes/class-gdo-application.php'); audit=t('includes/class-gdo-audit.php'); rate=t('includes/class-gdo-rate-limiter.php'); risk=t('includes/class-gdo-risk.php'); quality=t('includes/class-gdo-quality.php'); state=t('includes/class-gdo-state.php'); claims=t('includes/class-gdo-claims.php'); rest=t('includes/class-gdo-rest.php'); evidence=t('includes/class-gdo-evidence.php'); privacy=t('includes/class-gdo-privacy.php'); member=t('includes/class-gdo-membership-adapter.php'); migration=t('includes/class-gdo-migration.php'); notify=t('includes/class-gdo-notifications.php'); adv=t('includes/class-gdo-advanced-trust.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); events=t('includes/class-gdo-advanced-trust-events.php'); storage=t('includes/class-gdo-storage.php'); ops=t('includes/class-gdo-operations.php'); integ=t('includes/class-gdo-integration-contracts.php'); retention=t('includes/class-gdo-retention.php'); trace=t('TRACEABILITY.md'); status=t('STATUS.md'); manifest=t('RELEASE-MANIFEST-1.3.0.md'); readme=t('README.md'); workflow=t('.github/workflows/file09-rc2-final.yml'); release_files=[x for x in t('RELEASE-FILES.txt').splitlines() if x.strip()]; lock=json.loads(t('RELEASE-LOCK.json'))
checks=[]
def c(n,topic,ok): checks.append((n,topic,bool(ok)))
# R01-R03 frozen-baseline/governance sanity.
c(1,'Canonical File09 runtime/schema identity remains 1.3.0/core 6/Advanced Trust 2',has(main,'Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )") and has(hard,'const SCHEMA_VERSION = 2'))
c(2,'Repository truth still separates staging/live/operational',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
c(3,'Latest central/File09/Advanced-Trust ownership trace remains explicit',has(trace,'F09-CEN-01','F09-CEN-02','F09-AT-24'))
# R04-R20 defects discovered on frozen R10 head 91d9a590... and corrected during R11.
c(4,'Audit previous-hash read isolates database error state before chain read',has(audit,"$wpdb->last_error = ''",'$previous_raw = $wpdb->get_var','gdo_audit_chain_read_failed'))
c(5,'Rate limiter isolates post-upsert counter read database state',has(rate,"$wpdb->last_error = ''",'$raw_hits = $wpdb->get_var','gdo_rate_limit_query'))
c(6,'Risk reads isolate DB uncertainty and resolution distinguishes store failure from conflict',has(risk,"$wpdb->last_error = ''",'gdo_risk_resolution_store','gdo_risk_resolution_conflict'))
c(7,'Quality completion distinguishes database store failure from pending-state conflict',has(quality,'gdo_quality_store_failed','gdo_quality_conflict'))
c(8,'State transition distinguishes database write failure from optimistic concurrency',has(state,'gdo_transition_store_failed','gdo_concurrent_change'))
c(9,'Professional claim update/publish paths distinguish store/read failure from concurrency',has(claims,'gdo_claim_store_failed','gdo_claim_concurrent_change',"$wpdb->last_error = ''",'if ( ! empty( $wpdb->last_error ) || ! $application_id )'))
c(10,'REST autosave verifies the post-write application reload before reporting success',has(rest,'gdo_application_autosave_reload_failed','gdo_application_autosave_reload_missing','$fresh = GDO_Application::get'))
c(11,'Application create/save/consent paths preserve DB failure versus ordinary state conflict',has(app,'gdo_application_create_recovery_query','gdo_application_create_reload_query','gdo_draft_store_failed','gdo_consent_link_store'))
c(12,'Evidence critical reads have checked variants and review/grant store failures are explicit',has(evidence,'records_checked','current_checked','gdo_evidence_review_store_failed','gdo_evidence_grant_cleanup_failed'))
c(13,'Privacy export/erasure uses checked evidence inventory and pauses on uncertainty',has(privacy,'GDO_Evidence::records_checked','Erasure is paused because credential evidence inventory could not be read safely.',"$wpdb->last_error = ''"))
c(14,'Reviewer authorization/case reads fail closed under database uncertainty',has(member,"$wpdb->last_error = ''",'reviewer_scope_allows','reviewer_case_allows','return false;'))
c(15,'Legacy migration checks application/duplicate/version reads before mutation',has(migration,'Legacy File 09 application inventory could not be read safely.','Legacy credential duplicate state could not be read safely.','Legacy credential version state could not be read safely.'))
c(16,'Notification outbox duplicate recovery is fail-visible and provider exceptions are minimized',has(notify,'gdo_notification_outbox_query','doctor_verification_outbox_provider_exception','provider_no_explicit_success'))
c(17,'Base Advanced Trust jurisdiction/conflict mutations distinguish uncertain reads/store failure',has(adv,'gdo_jurisdiction_rule_query','gdo_conflict_resolve_store'))
c(18,'Hardened reverification scheduling distinguishes application DB uncertainty from missing application',has(hard,'gdo_reverification_application_query','Professional application state could not be read safely for reverification scheduling.'))
c(19,'Advanced Trust adverse-event bridge audits application-read failure instead of silently dropping it',has(events,'doctor_continuous_verification_application_read_failed',"$wpdb->last_error = ''"))
c(20,'Repository hygiene excludes generated Python caches and secret/build artifacts',has(t('.gitignore'),'__pycache__/','*.py[cod]','dist/','*.pem','*.key') and not any('__pycache__' in p.parts or p.suffix in {'.pyc','.pyo'} for p in root.rglob('*') if '.git' not in p.parts))
# R21-R80 fresh controls after correction.
c(21,'Application transitions remain row-lock/version guarded',has(state,'FOR UPDATE','row_version','can_transition'))
c(22,'Transition audit remains chained and fail-closed',has(audit,'previous_hash','event_hash','gdo_audit_chain_read_failed'))
c(23,'Submission remains snapshot/idempotency bound',has(app,'submission_hash','hash_equals( (string) $app->submission_hash, $submission_hash )'))
c(24,'Professional evidence still requires explicit license validity/registry review',has(evidence,'gdo_license_review',"'verified','active','matched'",'validity_until'))
c(25,'Evidence review remains current reviewer/capability/step-up/case bound',has(evidence,'gdo_evidence_review_forbidden','reviewer_scope_allows','reviewer_case_allows','recent_step_up'))
c(26,'Evidence grants remain one-time/session-bound',has(evidence,'session_digest','used_at','gdo_evidence_grant_conflict'))
c(27,'Credential review bytes retain watermark/no-download controls',has(evidence,'PRIVATE REVIEW','gdo_watermark_pdf_bytes','gdo_pdf_watermark_provider'))
c(28,'Private storage rechecks health before reads/deletes',has(storage,'public static function read','public static function delete_verified','self::health()'))
c(29,'Private storage rejects public/symlink/path traversal exposure',has(storage,'outside the public uploads directory','realpath','symlink'))
c(30,'Core future schema remains fail closed',has(migration,'gdo_schema_future_version','$current > GDO_SCHEMA_VERSION'))
c(31,'Core migration remains locked/idempotent with physical verification',has(migration,"const LOCK_OPTION = 'gdo_schema_migration_lock'",'gdo_migration_locked','GDO_Schema::verify_installation()'))
c(32,'Advanced Trust future schema remains fail closed',has(hard,'gdo_advanced_schema_future_version','$current_schema > self::SCHEMA_VERSION'))
c(33,'Advanced Trust physical table/index postconditions remain verified',has(hard,'SHOW INDEX FROM','gdo_advanced_schema_index_read','gdo_advanced_schema_index'))
c(34,'Hardening explicitly replaces unsafe RC5 lifecycle callbacks',has(hard,"remove_action( 'gdo_trust_continuous_monitor'","remove_action( 'gdo_application_submitted'","remove_action( 'gdo_application_decided'"))
c(35,'Continuous verification retains exclusive processing lease/stale recovery',has(hard,"monitor_status='processing'",'processing_lease_expired','release_monitor_claim'))
c(36,'Provider failure becomes degraded fact rather than owner decision',has(hard,'$provider_failure = true','degraded','gdo_continuous_verification_adverse_result'))
c(37,'Continuous monitor still does not directly transition professional state','GDO_State::transition' not in hard[hard.index('public static function continuous_monitor'):hard.index('public static function cleanup_upload_sessions')])
c(38,'Event-driven reverification remains bounded/distinct',has(hard,'gdo_trust_reverification_wakeup','wp_schedule_single_event','schedule_wakeup'))
c(39,'Public passport lookup rechecks current professional truth',has(hard,'verify_passport_uuid','identity_assurance_current','public_verified'))
c(40,'Public passport response remains no-store/no-cache',has(hard,"Cache-Control', 'no-store, max-age=0, must-revalidate'","Pragma', 'no-cache'"))
c(41,'Passport projection grants neither cure guarantee nor clinical authorization',has(hard,"'cure_guarantee'=>false","'clinical_authorization'=>false"))
c(42,'Passport issue remains serialized/versioned',has(hard,'SELECT MAX(version)','FOR UPDATE','gdo_passport_store'))
c(43,'Jurisdiction rules remain second-reviewer approved and immutable by approved version',has(hard,'gdo_jurisdiction_rule_separation','gdo_jurisdiction_rule_immutable','approved_by'))
c(44,'Issuer registry/review remains runtime and privileged-step-up gated',has(adv,'gdo_issuer_runtime_not_ready','gdo_issuer_review_runtime_not_ready','current privileged step-up'))
c(45,'External provider payloads remain minimized/bounded',has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
c(46,'Persisted provider arrays filter secret/token/key fields',has(adv,'secret|password|token|api[_-]?key|private[_-]?key|credential'))
c(47,'AI/equivalency/translation remain reviewer-assistance facts only',has(adv,'ai_assistance','equivalency_assessment','translation_assistance','reviewer-assistance adapters only'))
c(48,'Reviewer conflict declaration remains explicit/auditable',has(adv,'declare_conflict','doctor_reviewer_conflict_declared','reason_hash'))
c(49,'Reviewer conflict uncertainty remains deny-by-default',has(adv,'gdo_conflict_query','fail-closed conflict'))
c(50,'Conflict resolution remains privileged/step-up controlled',has(adv,'resolve_conflict','Conflict resolution requires privileged authorization and step-up'))
c(51,'Adaptive dual review remains human/monotonic',has(adv,'requires_dual_review','gdo_requires_dual_review'))
c(52,'Reviewer routing remains bounded and conflict-aware',has(adv,'smart_reviewer_candidates','has_conflict'))
c(53,'Reviewer calibration remains aggregate/bounded',has(adv,'reviewer_calibration','agreement_rate','overturn_rate'))
c(54,'Risk explanation remains human-review-required',has(adv,'risk_explanation','human_review_required','opaque_rejection_forbidden'))
c(55,'Risk recording remains runtime gated and DB failures explicit',has(risk,'gdo_risk_runtime_not_ready','gdo_risk_query_failed','gdo_risk_store_failed'))
c(56,'Risk resolution reauthorizes current actor',has(risk,'gdo_risk_resolution_forbidden','get_current_user_id','recent_step_up'))
c(57,'Notification producer remains File19 sun.event.v1 minimized transport',has(notify,'sun.event.v1','Never forward the raw event payload','sun_ingest_domain_event'))
c(58,'Outbox remains durable retry/dead-letter with checked persistence',has(notify,'doctor_verification_outbox_dead_letter','gdo_outbox_delivery_persist_failed','gdo_outbox_failure_persist_failed'))
c(59,'File09 still creates no parallel wp_mail transport','wp_mail(' not in notify)
c(60,'Dead-letter replay remains current-manager/recent-step-up authorized',has(notify,'gdo_outbox_replay_forbidden',"$actor_id !== get_current_user_id()",'recent_step_up'))
c(61,'Professional claims remain signed/version-bound and explicit-acceptance consumed',has(claims,'GDO_CLAIM_SIGNING_KEY','claim_version','signature') and has(notify,'did not explicitly accept the claim'))
c(62,'File00 current identity assurance remains required',has(member,'identity_assurance_current','self::sanctioned','self::base_assertion'))
c(63,'File02 recent step-up remains current-session bound',has(member,'recent_step_up','$user_id !== get_current_user_id()','SA_Professional_Reauthentication::assertion'))
c(64,'Reviewer private-evidence scope remains File00 + active-case constrained',has(member,'reviewer_scope_allows','reviewer_case_allows','assigned_reviewer_id'))
c(65,'Safe Mode still blocks ordinary mutations',has(ops,'mutation_allowed','safe_mode'))
c(66,'Controlled repair/Safe Mode changes reauthorize current manager and step-up',has(ops,'gdo_repair_forbidden','gdo_safe_mode_forbidden','recent_step_up'))
c(67,'Operational health still covers schema/storage/schedulers/dependencies',has(ops,'schema_version','advanced_trust_schema','private_storage','retention_cron','outbox_cron','trust_monitor_cron'))
c(68,'Operational reconciliation remains bounded/failure-visible',has(ops,'public static function reconcile','gdo_reconcile_query_failed','gdo_reconcile_commit_failed'))
c(69,'Privacy export remains paginated/minimized',has(privacy,'public function export( $email, $page = 1 )','$per = 20','LIMIT %d OFFSET %d'))
c(70,'Native privacy erasure invokes Advanced Trust and honors legal hold',has(privacy,'privacy_erase_application','GDO_Advanced_Trust_Hardening','legal_hold'))
c(71,'Advanced Trust privacy erasure remains atomic',has(hard,'gdo_privacy_advanced_transaction','gdo_privacy_advanced_commit',"$wpdb->query('ROLLBACK')"))
c(72,'Retention refuses unsafe active professional states and propagates failure',has(retention,"array( 'verified','reinstated','under_review','recommended','appeal_pending','submitted','resubmitted','renewal_due' )",'retention_failure'))
c(73,'Resumable cleanup remains hardened/failure-visible',has(hard,'cleanup_upload_sessions','gdo_upload_cleanup_unsafe_path'))
c(74,'Canonical File20 shell integration remains adapter-only',has(integ,'gdo.file09.owner-contract','sabri_shell_page_contracts'))
c(75,'Files03/07/08/21/23/26 consume public-safe verification projections',has(integ,'gdo.file03.doctor-profile-eligibility','gdo.file07.directory-eligibility','gdo.file08.clinic-eligibility','gdo.file21.publishing-eligibility','gdo.file23.publishing-dashboard-eligibility','gdo.file26.doctor-verification-projection'))
c(76,'File26 excludes private evidence and donor ranking advantage',has(integ,"'evidence_exposed'","'donor_rank_advantage'","'private_indexing' => false"))
c(77,'All 17 FR identifiers remain traceable',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)))
c(78,'All 10 NFR and 24 Advanced Trust identifiers remain traceable',all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)) and all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
c(79,'Ten prior 80-round ledgers remain preserved as historical evidence',all((root/x).exists() for x in ['REVIEW-80-ROUNDS-RC6.md','REVIEW-80-ROUNDS-RC6-R2.md','REVIEW-80-ROUNDS-RC6-R3.md','REVIEW-80-ROUNDS-RC6-R4.md','REVIEW-80-ROUNDS-RC6-R5.md','REVIEW-80-ROUNDS-RC6-R6.md','REVIEW-80-ROUNDS-RC6-R7.md','REVIEW-80-ROUNDS-RC6-R8.md','REVIEW-80-ROUNDS-RC6-R9.md','REVIEW-80-ROUNDS-RC6-R10.md']))
c(80,'Eleventh fresh ledger/gate/release-lock/62-entry package truth are synchronized',(root/'REVIEW-80-ROUNDS-RC6-R11.md').exists() and lock.get('eleventh_review_baseline')=='91d9a590e18e02030e27ed558ad2147981332ed3' and lock.get('eleventh_review_rounds')==80 and lock.get('eleventh_defect_rounds')==17 and lock.get('eleventh_clean_rounds')==63 and lock.get('release_file_count')==len(release_files)==62 and 'tests/eighty-round-audit-r11.py' in workflow and '62-entry' in manifest and 'Eleventh fresh 80-round' in status and 'Eleventh fresh 80-round' in readme))
failed=[x for x in checks if not x[2]]
for n,topic,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {topic}')
print(f'File 09 RC6 eleventh fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
defects=set(range(4,21))
print('Defect-bearing rounds:', ','.join(f'{n:02d}' for n in sorted(defects)))
print('Clean rounds:', ','.join(f'{n:02d}' for n in range(1,81) if n not in defects))
raise SystemExit(1 if failed else 0)
