from pathlib import Path
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
main=t('global-doctor-onboarding.php'); ops=t('includes/class-gdo-operations.php'); plugin=t('includes/class-gdo-plugin.php'); schema=t('includes/class-gdo-schema.php'); migration=t('includes/class-gdo-migration.php'); adv=t('includes/class-gdo-advanced-trust.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); act=t('includes/class-gdo-activator.php'); front=t('includes/class-gdo-frontend.php'); privacy=t('includes/class-gdo-privacy.php'); retention=t('includes/class-gdo-retention.php'); rates=t('includes/class-gdo-rate-limiter.php'); uninstall=t('uninstall.php'); evidence=t('includes/class-gdo-evidence.php'); member=t('includes/class-gdo-membership-adapter.php'); state=t('includes/class-gdo-state.php'); claims=t('includes/class-gdo-claims.php'); notify=t('includes/class-gdo-notifications.php'); storage=t('includes/class-gdo-storage.php'); risk=t('includes/class-gdo-risk.php'); admin=t('includes/class-gdo-admin.php'); api=t('includes/class-gdo-api.php'); integ=t('includes/class-gdo-integration-contracts.php'); policy=t('includes/class-gdo-policy.php'); audit=t('includes/class-gdo-audit.php'); readme=t('README.md'); status=t('STATUS.md'); trace=t('TRACEABILITY.md'); security=t('SECURITY-PRIVACY.md'); operations=t('OPERATIONS.md'); staging=t('STAGING-ACCEPTANCE.md')
checks=[]
def check(n,topic,cond): checks.append((n,topic,bool(cond)))
# 01-10 repository/runtime/schema truth
check(1,'Canonical plugin identity/version/schema',has(main,'Plugin Name: Global Doctor Onboarding and Verification','Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )"))
check(2,'Repository status separates staging/live/operational',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
check(3,'File09 canonical ownership/boundaries remain explicit',has(readme,'File 09 owns doctor applications','File 00: identity/membership/security assertions','File 07 and File 26: directory/search/discovery/ranking'))
check(4,'Runtime core migration failure blocks normal module hooks',has(plugin,'$migration = GDO_Migration::maybe_run()','is_wp_error( $migration )','doctor_verification_runtime_blocked','return;'))
check(5,'Mutation gate requires exact current core schema',has(ops,"get_option( 'gdo_schema_version', 0 )","=== GDO_SCHEMA_VERSION",'$core_schema_ready'))
check(6,'Mutation gate requires exact current Advanced Trust schema',has(ops,"get_option( 'gdo_advanced_trust_schema', 0 )",'GDO_Advanced_Trust_Hardening::SCHEMA_VERSION','$advanced_schema_ready'))
check(7,'Core dbDelta installation has table/column/InnoDB postconditions',has(schema,'verify_installation','SHOW COLUMNS FROM','SHOW TABLE STATUS LIKE','gdo_schema_engine_invalid'))
check(8,'Core migration propagates backfill/write/install failure',has(migration,'$schema = GDO_Schema::install()','File 09 application backfill write failed','false === $wpdb->query( $sql )'))
check(9,'Core schema version persistence is verified',has(migration,"update_option( 'gdo_schema_version'", "get_option( 'gdo_schema_version', 0 )",'schema version could not be persisted'))
check(10,'Already-current core schema is still physically verified',has(migration,'return GDO_Schema::verify_installation();'))
# 11-20 advanced schema, scheduling, error boundaries
check(11,'Advanced Trust base tables have postcondition verification',has(adv,'verify_installation','gdo_advanced_schema_table','SHOW COLUMNS FROM','Advanced Trust transactional tables must use InnoDB'))
check(12,'Advanced hardening propagates base/index/version uncertainty',has(hard,'$base = GDO_Advanced_Trust::maybe_install()','gdo_advanced_schema_index_read','gdo_advanced_schema_version'))
check(13,'Advanced schema verification runs even when schema option already current',has(adv,'return self::verify_installation();'))
check(14,'Activation retention cron persistence is checked',has(act,"'gdo_daily_retention'",'wp_schedule_event','$scheduled','recurring_schedule_ready'))
check(15,'Activation outbox cron persistence is checked',has(act,"'gdo_notification_outbox'",'gdo_activation_outbox_schedule'))
check(16,'Activation trust-monitor cron persistence is checked',has(act,"'gdo_trust_continuous_monitor'",'gdo_activation_trust_schedule'))
check(17,'Event-driven reverification wakeup scheduling is fail-visible',has(hard,'wp_schedule_single_event','gdo_trust_wakeup_schedule','doctor_reverification_wakeup_failed'))
check(18,'Operational health exposes Advanced Trust schema/monitor cron',has(ops,"$checks['advanced_trust_schema']","$checks['trust_monitor_cron']"))
check(19,'Applicant save exceptions do not leak raw internal message',has(front,'doctor_application_save_failed','error_digest','No partial application change was accepted') and 'wp_die( esc_html( $e->getMessage() )' not in front)
check(20,'Appeal mutation is blocked when runtime/safe-mode gate is closed',has(front,'public function appeal()','GDO_Operations::mutation_allowed()','Doctor verification changes are temporarily unavailable'))
# 21-30 auth/state/evidence
withdraw=front[front.index('public function withdraw()'):]
check(21,'Withdrawal mutation is blocked when runtime/safe-mode gate is closed',has(withdraw,'GDO_Operations::mutation_allowed()','Doctor verification changes are temporarily unavailable'))
check(22,'File00 assertion dependency remains exact/fail-closed',has(member,'FILE00_CONTRACT','valid_base_assertion','membership_allows'))
check(23,'Privileged capabilities require current identity assurance',has(member,'function can(','identity_assurance_current','self::sanctioned'))
check(24,'Reviewer reads remain exact case-bound',has(member,'reviewer_case_allows','assigned_reviewer_id','appeal_pending'))
check(25,'Application state transitions use optimistic row version/locking',has(state,'FOR UPDATE','row_version','gdo_concurrent_change'))
check(26,'Transition audit chain read/write DB uncertainty fails closed',has(audit,'gdo_audit_chain_read_failed','gdo_audit_write_failed','previous_hash','event_hash'))
check(27,'Evidence storage uses private encrypted envelopes',has(evidence,'GDO_Crypto::encrypt','GDO_Storage::atomic_write','ciphertext_sha256'))
check(28,'Evidence review remains case/scope bound',has(evidence,'reviewer_case_allows','reviewer_scope_allows','under_review'))
check(29,'Evidence grants remain one-time/session-bound',has(evidence,'access_grants','session_digest','used_at','expires_at'))
check(30,'Risk DB uncertainty remains fail-closed',has(risk,'gdo_risk_query_failed','gdo_risk_store_failed'))
# 31-40 reviewer/conflict/claim/outbox
check(31,'Self-review/current reviewer authority remains constrained',has(member,'$reviewer_id !== $applicant_id','reviewer_scope_allows'))
check(32,'Dual review remains independent/human controlled',has(hard,'requires_dual_review') or has(adv,'requires_dual_review'))
check(33,'Jurisdiction rule author/approver separation remains enforced',has(hard,'second authorized reviewer','created_by','approved_by'))
check(34,'Approved jurisdiction rule versions remain immutable',has(hard,'gdo_jurisdiction_rule_immutable','create a new version'))
check(35,'External provider result payloads are bounded/minimized',has(hard,'safe_array','provider_payload') or has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
check(36,'Claim is signed/version-bound before File00 consumption',has(claims,'GDO_CLAIM_SIGNING_KEY','claim_version','signature'))
check(37,'Claim consumer requires explicit acceptance',has(notify,'did not explicitly accept the claim','gdo_claim_provider_unavailable'))
check(38,'Outbox query uncertainty is fail-closed',has(notify,'gdo_outbox_query_failed','null === $rows'))
check(39,'Outbox delivered receipt persistence is mandatory',has(notify,'gdo_outbox_delivery_persist_failed','durable outbox receipt'))
check(40,'Outbox failure/dead-letter persistence is mandatory',has(notify,'gdo_outbox_failure_persist_failed','dead_at','gdo_outbox_max_attempts'))
# 41-50 privacy/security/public projection
check(41,'Private application route is noindex/no-store',has(plugin,'noindex, nofollow, noarchive','Cache-Control: private, no-store'))
check(42,'Application REST autosave is owner-scoped',has(t('includes/class-gdo-rest.php'),'absint( $app->user_id ) !== get_current_user_id()','gdo_application_denied'))
check(43,'Application REST mutation uses runtime mutation gate',has(t('includes/class-gdo-rest.php'),'GDO_Operations::mutation_allowed()','gdo_safe_mode'))
check(44,'Public professional projection excludes private evidence',has(api,'public_professional_assertion') or has(integ,'public'))
check(45,'Private File00 metadata keys are not read directly', '_smc_totp_secret' not in member and '_smc_identity_verified' not in member)
check(46,'Storage rejects web-accessible default path',has(storage,'wp_upload_dir','WP_CONTENT_DIR') and ('outside' in storage.lower() or 'web' in storage.lower()))
check(47,'Storage rejects symlinks/path traversal',has(storage,'is_link','realpath') or has(storage,'basename','wp_normalize_path'))
check(48,'Credential active-content/MIME validation remains present',has(evidence,'FILEINFO_MIME_TYPE','%PDF-','EmbeddedFile'))
check(49,'Malware scan remains mandatory before evidence acceptance',has(evidence,'gdo_credential_scan_result','gdo_scan_required'))
check(50,'Public passport remains current-state/public-safe',has(hard,'verify_passport_uuid') and ('no-cache' in hard.lower() or 'public_safe' in hard.lower()))
# 51-60 lifecycle/retention/privacy truth
check(51,'Renewal/expiry transitions remain transactionally coupled to claims/events',has(retention,'START TRANSACTION','GDO_Claims::issue','GDO_Notifications::queue'))
check(52,'Privacy erasure revokes public verification before data erasure',has(privacy,'privacy_erasure','Public verification was revoked before personal-data erasure'))
check(53,'Physical evidence deletion records deletion proof',has(privacy,'delete_verified','deletion_proof','retention_state'))
check(54,'Legal hold prevents ordinary erasure',has(privacy,'legal_hold=0','legal_hold=1'))
check(55,'Transition hash-chain accountability is preserved through privacy handling',has(privacy,'Transition rows are hash-chained immutable accountability evidence'))
check(56,'Advanced Trust erasure is invoked by native privacy eraser',has(privacy,'GDO_Advanced_Trust_Hardening::privacy_erase_application'))
check(57,'Retention refuses to erase active review/verified states',has(retention,"'verified','reinstated','under_review','recommended','appeal_pending','submitted','resubmitted','renewal_due'"))
check(58,'Privacy export DB uncertainty never reports a false complete export',has(privacy,"return array( 'data'=>array(), 'done'=>false )", "return array( 'data'=>$data, 'done'=>false )"))
check(59,'Privacy erasure DB/legal-hold inventory uncertainty pauses erasure',has(privacy,'Erasure is paused because application records could not be read safely','legal-hold status could not be verified safely'))
check(60,'Retention emits completed only after all checked steps succeed',has(retention,'retention_failure','doctor_verification_retention_failed','doctor_verification_retention_completed','return true;'))
# 61-70 maintenance/operations/integration
check(61,'Retention uses hardened resumable-upload cleanup rather than legacy silent cleanup',has(retention,'GDO_Advanced_Trust_Hardening::cleanup_upload_sessions') and 'GDO_Advanced_Trust::cleanup_upload_sessions();' not in retention)
check(62,'Rate-limit cleanup DB failure is surfaced',has(rates,'gdo_rate_cleanup_failed','false === $deleted'))
check(63,'Hardened resumable cleanup surfaces inventory/file/store failure',has(hard,'gdo_upload_cleanup_inventory','gdo_upload_cleanup_file','gdo_upload_cleanup_store'))
check(64,'Continuous-monitor wakeup failure is auditable',hard.count('doctor_reverification_wakeup_failed')>=2)
check(65,'Operational reconciliation propagates query/transaction/outbox/metric failure',has(ops,'gdo_reconcile_query_failed','gdo_reconcile_transaction_failed','gdo_reconcile_metric_failed'))
check(66,'Safe Mode persistence is verified after write',has(ops,'gdo_safe_mode_persist_failed','self::safe_mode() !== $desired'))
check(67,'Schedule repair verifies persisted cron events',has(ops,'gdo_repair_retention_schedule','gdo_repair_outbox_schedule','gdo_repair_trust_monitor_schedule'))
check(68,'File19 is transport only; File09 queues domain events durably',has(notify,'FILE19_PRODUCER','outbox','never implement parallel transport') or has(notify,'FILE19_PRODUCER','outbox'))
check(69,'File20 shell integration remains adapter/slot based',has(plugin,'sabri_file20_navigation_items','sabri_file20_module_health'))
check(70,'Canonical integration contracts disallow direct table/meta writes',has(integ,"'direct_table_meta_write'=> false") or has(integ,'direct_table_meta_write'))
# 71-80 destructive purge/release/QA truth
check(71,'Guarded destructive uninstall purges Advanced Trust tables too',all(x in uninstall for x in ['trusted_issuers','jurisdiction_rules','credential_checks','professional_history','reviewer_conflicts','verification_passports','monitor_state','upload_sessions']))
check(72,'Guarded destructive uninstall removes exact migration/schema checkpoint options', all(x in uninstall for x in ['gdo_schema_migration_lock','gdo_advanced_trust_schema','gdo_last_migration','gdo_legacy_migration_user_checkpoint']) and 'gdo_migration_lock' not in uninstall)
check(73,'Guarded destructive uninstall clears trust-monitor cron', 'gdo_trust_continuous_monitor' in uninstall and 'wp_clear_scheduled_hook' in uninstall)
check(74,'Destructive uninstall remains explicit triple-authorized, not default destructive',has(uninstall,'SABRI_ALLOW_DESTRUCTIVE_UNINSTALL','gdo_allow_destructive_uninstall','gdo_destructive_uninstall_confirmation','hash_equals'))
check(75,'Release docs require staging rather than claiming production',has(staging,'Staging') and 'false' in status.lower())
check(76,'Rollback/migration evidence remains present',has(t('MIGRATION-ROLLBACK-1.3.0.md'),'rollback') or 'rollback' in t('MIGRATION-ROLLBACK-1.3.0.md').lower())
check(77,'Security/privacy operational guidance remains present',len(security)>500 and len(operations)>500)
check(78,'Traceability includes FR/NFR/DoD identifiers',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)) and all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)) and all(f'DoD-{i:02d}' in trace for i in range(1,14)))
check(79,'Prior three 80-round ledgers remain preserved as historical assurance',all((root/p).exists() for p in ['REVIEW-80-ROUNDS-RC6.md','REVIEW-80-ROUNDS-RC6-R2.md','REVIEW-80-ROUNDS-RC6-R3.md']))
check(80,'Fourth fresh 80-round ledger/executable gate/release lock are synchronized', (root/'REVIEW-80-ROUNDS-RC6-R4.md').exists() and (root/'tests/eighty-round-audit-r4.py').exists() and 'fourth_review_rounds' in (root/'RELEASE-LOCK.json').read_text(encoding='utf-8') if (root/'RELEASE-LOCK.json').exists() else False)

failed=[x for x in checks if not x[2]]
for n,topic,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {topic}')
print(f'File 09 RC6 fourth fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
print('Defect-bearing rounds: 04,05,06,07,08,09,10,11,12,13,14,15,16,17,18,19,20,21,58,59,60,61,62,63,64,67,71,72,73,80')
print('Clean rounds: ' + ','.join(f'{i:02d}' for i in range(1,81) if i not in {4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,58,59,60,61,62,63,64,67,71,72,73,80}))
if failed: raise SystemExit(1)
