from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
main=t('global-doctor-onboarding.php'); ops=t('includes/class-gdo-operations.php'); migration=t('includes/class-gdo-migration.php'); admin=t('includes/class-gdo-admin.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); adv=t('includes/class-gdo-advanced-trust.php'); risk=t('includes/class-gdo-risk.php'); quality=t('includes/class-gdo-quality.php'); schema=t('includes/class-gdo-schema.php'); evidence=t('includes/class-gdo-evidence.php'); storage=t('includes/class-gdo-storage.php'); crypto=t('includes/class-gdo-crypto.php'); privacy=t('includes/class-gdo-privacy.php'); retention=t('includes/class-gdo-retention.php'); claims=t('includes/class-gdo-claims.php'); notify=t('includes/class-gdo-notifications.php'); state=t('includes/class-gdo-state.php'); plugin=t('includes/class-gdo-plugin.php'); integ=t('includes/class-gdo-integration-contracts.php'); trace=t('TRACEABILITY.md'); status=t('STATUS.md'); workflow=t('.github/workflows/file09-rc2-final.yml'); uninstall=t('uninstall.php')
checks=[]
def c(n,name,ok): checks.append((n,name,bool(ok)))
c(1,'Runtime/version/schema identity',has(main,'Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )"))
c(2,'Repository/staging/live truth separation',has(status.lower(),'staging accepted: false','live deployed: false'))
c(3,'Latest File09/Advanced Trust plan trace',all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
c(4,'Mutation readiness includes claim signing key',has(ops,"defined( 'GDO_CLAIM_SIGNING_KEY' )","strlen( (string) GDO_CLAIM_SIGNING_KEY ) >= 32"))
c(5,'Health-count DB error isolation',has(ops,'private static function count_query',"$wpdb->last_error = '';","A File 09 health query could not be completed safely."))
recon=ops[ops.index('public static function reconcile'):ops.index('public static function repair')]
c(6,'Reconciliation DB error isolation',has(recon,"$wpdb->last_error = '';",'gdo_reconcile_query_failed'))
repair=ops[ops.index('public static function repair'):ops.index('public static function set_safe_mode')]
c(7,'Controlled repair native authorization',has(repair,'gdo_repair_forbidden','sabri_manage_doctor_verification','recent_step_up'))
safe=ops[ops.index('public static function set_safe_mode'):ops.index('public static function record_metric')]
c(8,'Safe Mode native authorization',has(safe,'gdo_safe_mode_forbidden','sabri_manage_doctor_verification','recent_step_up'))
c(9,'Legacy migration table inventory DB uncertainty',has(migration,'Legacy File 09 table inventory could not be verified safely.',"$wpdb->last_error = '';"))
c(10,'Manager review queue DB uncertainty','The doctor-verification review queue is temporarily unavailable' in admin)
c(11,'Assigned reviewer queue DB uncertainty','The assigned doctor-verification review queue is temporarily unavailable' in admin)
c(12,'Reviewer risk projection DB uncertainty','Professional risk signals could not be read safely for this review.' in admin)
c(13,'Public passport revocation cache safety',has(hard,"'Cache-Control', 'no-store, max-age=0, must-revalidate'","'X-Robots-Tag', 'noindex, nofollow, noarchive'","'Referrer-Policy', 'no-referrer'"))
resolve=risk[risk.index('public static function resolve'):]
c(14,'Risk resolution native authorization',has(resolve,'gdo_risk_resolution_forbidden','sabri_manage_doctor_verification','recent_step_up','mutation_allowed'))
record=risk[risk.index('public static function record'):risk.index('public static function unresolved')]
c(15,'Risk recording Safe Mode gate',has(record,'gdo_risk_runtime_not_ready','mutation_allowed'))
complete=quality[quality.index('public static function complete_sample'):quality.index('public static function metrics')]
c(16,'Quality completion native authorization',has(complete,'gdo_quality_forbidden','gdo_quality_query_failed','sabri_manage_doctor_verification','recent_step_up'))
metrics=quality[quality.index('public static function metrics'):]
c(17,'Quality metrics DB uncertainty',has(metrics,"$wpdb->last_error = '';",'gdo_quality_metrics_query_failed'))
create=quality[quality.index('public static function create_sample'):quality.index('public static function complete_sample')]
c(18,'Quality sampling Safe Mode gate','GDO_Operations::mutation_allowed()' in create)
c(19,'Future core schema fail-closed',has(migration,'gdo_schema_future_version','$current > GDO_SCHEMA_VERSION'))
c(20,'Future Advanced Trust schema fail-closed',has(hard,'gdo_advanced_schema_future_version','$current_schema > self::SCHEMA_VERSION'))
c(21,'Core physical schema verification',has(schema,'SHOW COLUMNS FROM','SHOW TABLE STATUS LIKE','InnoDB'))
c(22,'Advanced Trust physical schema verification',has(adv,'verify_installation','gdo_advanced_schema_engine'))
c(23,'Trusted issuer independent review','gdo_issuer_review_separation' in adv)
c(24,'Jurisdiction independent approval',has(hard,'second authorized reviewer','gdo_jurisdiction_rule_separation'))
c(25,'Primary-source degraded/manual path',has(adv,'provider_unavailable','reviewer_required'))
c(26,'Provider payload minimization',has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
c(27,'AI human-final-decision invariant',has(adv,'human_final_decision_required','decision'))
c(28,'Equivalency advisory-only boundary',has(adv,'equivalency_assessment','legal_license_grant'))
c(29,'Fraud signal human-review invariant',has(adv,'fraud_ring_scan','credential_reuse_network'))
c(30,'Reviewer case binding',has(t('includes/class-gdo-membership-adapter.php'),'reviewer_case_allows','reviewer_scope_allows'))
c(31,'Adaptive dual review',has(adv,'requires_dual_review','gdo_requires_dual_review'))
c(32,'Encrypted private evidence',has(evidence,'GDO_Crypto::encrypt','GDO_Storage::atomic_write'))
c(33,'MIME/polyglot/malware fail-closed',has(evidence,'FILEINFO_MIME_TYPE','EmbeddedFile','gdo_scan_required'))
c(34,'Session-bound evidence grants',has(evidence,'session_digest','used_at','access_grants'))
c(35,'Viewing-room no-download contract',has(adv,'issue_viewing_room_grant',"'download_allowed'=>false"))
c(36,'Resumable upload ownership/state',has(adv,'create_upload_session','FOR UPDATE','gdo_upload_session_forbidden'))
c(37,'Chunk order/exactly-once',has(adv,'gdo_upload_chunk_order','received_chunks'))
c(38,'Chunk durability','fsync' in adv)
c(39,'Finalize hash/size verification',has(adv,"hash_file('sha256'",'gdo_upload_hash_mismatch'))
c(40,'Expired upload unsafe-path protection',has(hard,'unsafe_chunk_path','gdo_upload_cleanup_unsafe_path'))
c(41,'Canonical private-storage boundary',has(storage,'realpath( $dir )','canonical filesystem path'))
c(42,'Storage use-time health',has(storage,'public static function read','self::health()'))
c(43,'AES-256-GCM authentication',has(crypto,'aes-256-gcm','gdo_authentication_failure'))
c(44,'Privacy export failure propagation','gdo_advanced_export_failed' in privacy)
c(45,'Physical evidence deletion proof',has(evidence,'function delete_record_safely','deletion_proof','deletion_pending_erasure','deletion_pending_retention') and has(privacy,'GDO_Evidence::delete_record_safely') and has(retention,'GDO_Evidence::delete_record_safely'))
c(46,'Advanced Trust erasure checked operations',has(hard,'privacy_erase_application','gdo_privacy_operational_cleanup'))
c(47,'Legal-hold protection','legal_hold' in privacy)
c(48,'Retention runtime gate',has(retention,'gdo_retention_runtime_not_ready','mutation_allowed'))
c(49,'Signed/versioned professional claims',has(claims,'GDO_CLAIM_SIGNING_KEY','claim_version','signature'))
c(50,'Explicit File00 claim acceptance',has(notify,'did not explicitly accept the claim','gdo_claim_provider_unavailable'))
c(51,'File19 minimized event payload',has(notify,'Never forward the raw event payload','sun.event.v1'))
c(52,'Outbox persistence',has(notify,'gdo_outbox_delivery_persist_failed','gdo_outbox_failure_persist_failed'))
c(53,'Transition row lock/version',has(state,'FOR UPDATE','row_version'))
c(54,'Risk query fail-closed','gdo_risk_query_failed' in risk)
c(55,'File20 shell adapter boundary',has(plugin,'sabri_file20_navigation_items','sabri_file20_module_health'))
c(56,'File19 producer contract',has(notify,'sun_register_notification_producer','sun.event.v1'))
c(57,'File26 public projection boundary',has(integ,'gdo.file26.doctor-verification-projection','contract_tested'))
c(58,'File03/07/08 claim consumers',all(x in integ for x in ['gdo.file03','gdo.file07','gdo.file08']))
c(59,'Private evidence excluded from search',has(integ,'evidence_exposed','private_indexing','public_projection_class'))
c(60,'Donation/ranking neutrality',has(integ,'donor_rank_advantage','donor_neutral','paid_rank_advantage'))
c(61,'No cure guarantee/clinical authorization',has(adv,"'cure_guarantee'=>false","'clinical_authorization'=>false"))
c(62,'Public passport current-state recheck',has(hard,'verify_passport_uuid','identity_assurance_current','public_verified'))
c(63,'Public passport GET read-only',"$contract['public_get_mutates_owner_state'] = false" in hard)
monitor=hard[hard.index('public static function continuous_monitor'):hard.index('private static function unsafe_chunk_path')]
c(64,'Continuous monitoring no auto-revocation','revoke_passports_for_application' not in monitor)
c(65,'Recurring scheduler correctness',has(t('includes/class-gdo-activator.php'),'recurring_schedule_ready','wp_get_scheduled_event'))
c(66,'Operational health coverage',has(ops,'trust_monitor_cron','database_observability'))
c(67,'Ordinary admin Safe Mode enforcement','File 09 mutations are unavailable until Safe Mode is cleared' in admin)
c(68,'Destructive uninstall authorization',has(uninstall,'SABRI_ALLOW_DESTRUCTIVE_UNINSTALL','gdo_destructive_uninstall_confirmation'))
c(69,'Migration/rollback documentation',(root/'MIGRATION-ROLLBACK-1.3.0.md').is_file())
c(70,'Staging external mandatory gate',has(status.lower(),'staging accepted: false','live deployed: false'))
c(71,'All 17 FR traceable',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)))
c(72,'All 10 NFR traceable',all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)))
c(73,'All 24 Advanced Trust requirements traceable',all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
c(74,'File09 CEN ownership trace',has(trace,'F09-CEN-01','F09-CEN-02'))
c(75,'Search projection ownership trace','CEN-SEARCH-001' in trace)
c(76,'Applicant/reviewer acceptance journeys trace',has(trace,'AJ-03','AJ-04','AJ-05','AJ-31','AJ-40'))
c(77,'Exact-head checkout gate','Assert exact source head' in workflow)
c(78,'Deterministic double-build gate','Build twice and verify exact-head package' in workflow)
c(79,'Generated exact-head SBOM coverage',has(t('tools/verify-release.py'),'generated SBOM','source/package parity mismatch'))
lock=json.loads(t('RELEASE-LOCK.json')); release=[x for x in t('RELEASE-FILES.txt').splitlines() if x.strip()]
c(80,'R8 ledger/release-lock/workflow synchronization',(root/'REVIEW-80-ROUNDS-RC6-R8.md').is_file() and lock.get('eighth_review_baseline')=='f40228d29ffa92e8d27ea84f9b1c1ae4a63ff9b2' and lock.get('eighth_review_rounds')==80 and lock.get('eighth_defect_rounds')==15 and lock.get('eighth_clean_rounds')==65 and lock.get('release_file_count')==len(release) and 'tests/eighty-round-audit-r8.py' in workflow)
failed=[x for x in checks if not x[2]]
for n,name,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {name}')
print(f'File 09 RC6 eighth fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
print('Defect-bearing rounds on frozen baseline: 04,05,06,07,08,09,10,11,12,13,14,15,16,17,18')
if failed: raise SystemExit(1)
