from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def t(p): return (root/p).read_text(encoding='utf-8')
def has(s,*xs): return all(x in s for x in xs)
main=t('global-doctor-onboarding.php'); api=t('includes/class-gdo-api.php'); rest=t('includes/class-gdo-rest.php'); app=t('includes/class-gdo-application.php'); admin=t('includes/class-gdo-admin.php'); evidence=t('includes/class-gdo-evidence.php'); quality=t('includes/class-gdo-quality.php'); frontend=t('includes/class-gdo-frontend.php'); state=t('includes/class-gdo-state.php'); claims=t('includes/class-gdo-claims.php'); notify=t('includes/class-gdo-notifications.php'); risk=t('includes/class-gdo-risk.php'); hard=t('includes/class-gdo-advanced-trust-hardening.php'); adv=t('includes/class-gdo-advanced-trust.php'); member=t('includes/class-gdo-membership-adapter.php'); ops=t('includes/class-gdo-operations.php'); privacy=t('includes/class-gdo-privacy.php'); retention=t('includes/class-gdo-retention.php'); storage=t('includes/class-gdo-storage.php'); migration=t('includes/class-gdo-migration.php'); integ=t('includes/class-gdo-integration-contracts.php'); trace=t('TRACEABILITY.md'); status=t('STATUS.md'); manifest=t('RELEASE-MANIFEST-1.3.0.md'); readme=t('README.md'); workflow=t('.github/workflows/file09-rc2-final.yml'); release_files=[x for x in t('RELEASE-FILES.txt').splitlines() if x.strip()]; lock=json.loads(t('RELEASE-LOCK.json'))
checks=[]
def c(n,topic,ok): checks.append((n,topic,bool(ok)))
# R01-R03 frozen-baseline/governance sanity.
c(1,'Canonical File09 runtime/schema identity remains stable',has(main,'Version: 1.3.0',"define( 'GDO_SCHEMA_VERSION', 6 )"))
c(2,'Repository truth still separates staging/live/operational',has(status.lower(),'staging accepted: **false**','live deployed: **false**','operationally accepted: **false**'))
c(3,'Latest central/File09/Advanced-Trust trace remains explicit',has(trace,'F09-CEN-01','F09-CEN-02','F09-AT-24'))
# R04-R22 fresh defects on frozen R9 baseline ec3ca2dd... corrected during R10.
c(4,'Public verification projection distinguishes database uncertainty from not-applied',has(api,"'reason_code' => 'database_unavailable'","$wpdb->last_error = ''",'verification_record_for_user'))
c(5,'Private application REST reads/autosave surface DB uncertainty',has(rest,'gdo_application_read_failed','gdo_application_autosave_read_failed',"'status'=>503"))
c(6,'Privileged health permission requires current manager capability and recent step-up',has(rest,'public function operator()',"sabri_manage_doctor_verification",'recent_step_up( $user_id )'))
c(7,'Draft creation does not convert latest-application DB failure into no-application',has(app,'gdo_application_latest_query',"$wpdb->last_error = ''",'ensure_draft'))
c(8,'Consent owner command distinguishes application/history DB uncertainty',has(app,'gdo_consent_application_query','gdo_consent_history_query'))
c(9,'Submission row-lock read failure is fail-visible',has(app,'gdo_submit_application_query','The application submission state could not be read safely'))
c(10,'Admin application locking distinguishes DB failure from missing/conflict',has(admin,'The doctor application could not be locked/read safely.',"'response'=>503"))
c(11,'Reviewer eligibility profile/workload reads isolate DB uncertainty',has(admin,'gdo_reviewer_profile_query','gdo_reviewer_workload_unknown',"$wpdb->last_error = ''"))
c(12,'Reviewer/evidence/appeal assignment lock paths surface DB uncertainty',has(admin,'The reviewer profile could not be locked safely for assignment.','Credential evidence could not be read safely.','The appeal assignment state could not be read safely.'))
c(13,'Appeal resolution distinguishes DB failure from stale/no appeal',has(admin,'The appeal resolution state could not be read safely.'))
c(14,'Evidence upload application/current-evidence reads distinguish DB uncertainty',has(evidence,'gdo_evidence_application_query','gdo_evidence_current_query'))
c(15,'Evidence decrypt/key rotation reads distinguish DB failure and propagate keyring error',has(evidence,'gdo_decrypt_application_query','gdo_rotation_evidence_query','if ( is_wp_error( $ring ) ) { return $ring; }'))
c(16,'Quality-sample failure after committed decision is observable/audited',has(quality,'gdo_quality_runtime_not_ready','gdo_quality_sample_store') and has(admin,'doctor_verification_quality_sample_failed','is_wp_error( $quality_sample )'))
c(17,'Front-end application-state DB failure is explicit',has(frontend,'gdo_frontend_application_query','The private doctor application state could not be read safely.'))
c(18,'Applicant appeal application DB failure returns 503',has(frontend,'The appeal application state could not be read safely.',"'response'=>503"))
c(19,'Generic state transition distinguishes row-lock DB failure from invalid transition',has(state,'gdo_transition_application_query','application state could not be locked/read safely for transition'))
c(20,'Professional claim issuance distinguishes application DB failure from missing record',has(claims,'gdo_claim_application_query','professional claim application state could not be read safely'))
c(21,'Completeness preserves DB uncertainty and submission surfaces it',has(app,"'query_error'=>$query_error",'gdo_submit_completeness_query',"$wpdb->last_error = ''"))
c(22,'Draft save distinguishes application DB failure from ordinary access denial',has(app,'gdo_draft_application_query','The draft application could not be read safely.'))
# R23-R80 fresh post-correction controls.
c(23,'Application state transitions remain explicit and optimistic-concurrency guarded',has(state,'FOR UPDATE','row_version','gdo_concurrent_change'))
c(24,'Transition audit chain remains fail-closed and hashed',has(t('includes/class-gdo-audit.php'),'gdo_audit_chain_read_failed','event_hash','previous_hash'))
c(25,'Submission remains immutable/idempotency bound',has(app,'submission_hash','hash_equals( (string) $app->submission_hash, $submission_hash )','gdo_submit_state'))
c(26,'Accepted professional evidence requires registry/validity constraints',has(evidence,'gdo_license_review',"'verified','active','matched'",'validity_until'))
c(27,'Evidence review remains current-actor/capability/step-up/case bound',has(evidence,'gdo_evidence_review_forbidden','reviewer_scope_allows','reviewer_case_allows','recent_step_up'))
c(28,'Evidence grants remain one-time/session-bound and use-time authorized',has(evidence,'session_digest','used_at','gdo_evidence_grant_conflict','sabri_access_doctor_credentials'))
c(29,'Credential review bytes retain watermark/download-negative controls',has(evidence,'PRIVATE REVIEW','gdo_watermark_pdf_bytes','gdo_pdf_watermark_provider'))
c(30,'Private encrypted storage rechecks health before reads/deletes',has(storage,'public static function read','public static function delete_verified','self::health()'))
c(31,'Private storage rejects public/symlink/path-traversal exposure',has(storage,'outside the public uploads directory','realpath','symlink'))
c(32,'Core future schema fails closed',has(migration,'gdo_schema_future_version','$current > GDO_SCHEMA_VERSION'))
c(33,'Core migration remains locked/idempotent with delegated physical postconditions',has(migration,"const LOCK_OPTION = 'gdo_schema_migration_lock'",'gdo_migration_locked','GDO_Schema::verify_installation()'))
c(34,'Advanced Trust future schema fails closed',has(hard,'gdo_advanced_schema_future_version','$current_schema > self::SCHEMA_VERSION'))
c(35,'Advanced Trust physical schema/index postconditions remain verified',has(hard,'SHOW INDEX FROM','gdo_advanced_schema_index_read','gdo_advanced_schema_index'))
c(36,'Continuous verification uses exclusive processing lease and stale recovery',has(hard,"monitor_status='processing'",'processing_lease_expired','gdo_trust_monitor_claim_failed','release_monitor_claim'))
c(37,'Continuous monitor provider failure degrades facts rather than auto-deciding',has(hard,'$provider_failure = true','degraded','gdo_continuous_verification_adverse_result'))
c(38,'Continuous monitoring does not issue state transition/claim itself','GDO_State::transition' not in hard[hard.index('public static function continuous_monitor'):hard.index('public static function cleanup_upload_sessions')] and 'GDO_Claims::issue' not in hard[hard.index('public static function continuous_monitor'):hard.index('public static function cleanup_upload_sessions')])
c(39,'Event-driven reverification remains bounded/distinct',has(hard,'gdo_trust_reverification_wakeup','wp_schedule_single_event','schedule_wakeup'))
c(40,'Passport public lookup rechecks current File00/File09 truth',has(hard,'verify_passport_uuid','identity_assurance_current','public_verified'))
c(41,'Public passport remains non-cacheable',has(hard,"Cache-Control', 'no-store, max-age=0, must-revalidate'","Pragma', 'no-cache'"))
c(42,'Passport public projection grants neither cure guarantee nor clinical authorization',has(hard,"'cure_guarantee'=>false","'clinical_authorization'=>false"))
c(43,'Passport issue remains serialized/versioned',has(hard,'SELECT MAX(version)','FOR UPDATE','gdo_passport_store'))
c(44,'Jurisdiction rules remain independently approved and immutable by version',has(hard,'gdo_jurisdiction_rule_separation','gdo_jurisdiction_rule_immutable','approved_by'))
c(45,'Issuer registry/review remains privileged-step-up/runtime gated',has(adv,'gdo_issuer_runtime_not_ready','gdo_issuer_review_runtime_not_ready','current privileged step-up'))
c(46,'External provider payloads remain minimized/bounded',has(adv,'PROVIDER_PAYLOAD_MAX_BYTES','sanitize_provider_array'))
c(47,'Persisted provider arrays filter secret/token/key fields',has(adv,'secret|password|token|api[_-]?key|private[_-]?key|credential'))
c(48,'AI/equivalency/translation remain assistance facts only',has(adv,'ai_assistance','equivalency_assessment','translation_assistance') and 'reviewer-assistance adapters only' in adv)
c(49,'Reviewer conflict declaration remains explicit/auditable',has(adv,'declare_conflict','doctor_reviewer_conflict_declared','reason_hash'))
c(50,'Conflict uncertainty remains deny-by-default',has(adv,'gdo_conflict_query','fail-closed conflict'))
c(51,'Conflict resolution remains privileged/step-up controlled',has(adv,'resolve_conflict','Conflict resolution requires privileged authorization and step-up'))
c(52,'Dual-review remains human/monotonic',has(adv,'requires_dual_review','gdo_requires_dual_review'))
c(53,'Reviewer routing remains bounded/conflict aware',has(adv,'smart_reviewer_candidates','has_conflict'))
c(54,'Reviewer calibration remains aggregate and bounded',has(adv,'reviewer_calibration','agreement_rate','overturn_rate'))
c(55,'Risk explanation remains human-review-required',has(adv,'risk_explanation','human_review_required','opaque_rejection_forbidden'))
c(56,'Risk recording is runtime gated and DB failures are explicit',has(risk,'gdo_risk_runtime_not_ready','gdo_risk_query_failed','gdo_risk_store_failed'))
c(57,'Risk resolution reauthorizes current actor',has(risk,'gdo_risk_resolution_forbidden','get_current_user_id','recent_step_up'))
c(58,'Notification producer remains File19 sun.event.v1 minimized transport',has(notify,'sun.event.v1','Never forward the raw event payload','sun_ingest_domain_event'))
c(59,'Outbox remains durable retry/dead-letter with checked persistence',has(notify,'doctor_verification_outbox_dead_letter','gdo_outbox_delivery_persist_failed','gdo_outbox_failure_persist_failed'))
c(60,'File09 never creates parallel wp_mail transport','wp_mail(' not in notify)
c(61,'Dead-letter replay remains current-manager/step-up authorized',has(notify,'gdo_outbox_replay_forbidden',"$actor_id !== get_current_user_id()",'recent_step_up'))
c(62,'Professional claims remain signed/version-bound and explicit-acceptance consumed',has(claims,'GDO_CLAIM_SIGNING_KEY','claim_version','signature') and has(notify,'did not explicitly accept the claim'))
c(63,'File00 current identity assurance remains required',has(member,'identity_assurance_current','self::sanctioned','self::base_assertion'))
c(64,'File02 recent step-up remains current-session bound',has(member,'recent_step_up','$user_id !== get_current_user_id()','SA_Professional_Reauthentication::assertion'))
c(65,'Reviewer scope/private evidence remains File00 + active-case constrained',has(member,'reviewer_scope_allows','reviewer_case_allows','assigned_reviewer_id'))
c(66,'Safe Mode blocks ordinary mutations',has(ops,'mutation_allowed','safe_mode'))
c(67,'Controlled repair and Safe Mode changes reauthorize current manager + step-up',has(ops,'gdo_repair_forbidden','gdo_safe_mode_forbidden','recent_step_up'))
c(68,'Operational health covers schema/storage/schedulers/dependencies',has(ops,'schema_version','advanced_trust_schema','private_storage','retention_cron','outbox_cron','trust_monitor_cron'))
c(69,'Operational reconciliation is bounded and failure-visible',has(ops,'public static function reconcile','gdo_reconcile_query_failed','gdo_reconcile_commit_failed'))
c(70,'Privacy export remains paginated/minimized/failure-aware',has(privacy,'public function export( $email, $page = 1 )','$per = 20','LIMIT %d OFFSET %d'))
c(71,'Native privacy erasure invokes Advanced Trust erasure and respects legal hold',has(privacy,'privacy_erase_application','GDO_Advanced_Trust_Hardening','legal_hold'))
c(72,'Advanced Trust privacy erasure remains atomic',has(hard,'gdo_privacy_advanced_transaction','gdo_privacy_advanced_commit',"$wpdb->query('ROLLBACK')"))
c(73,'Retention refuses unsafe active professional states and propagates failure',has(retention,"array( 'verified','reinstated','under_review','recommended','appeal_pending','submitted','resubmitted','renewal_due' )",'retention_failure'))
c(74,'Resumable cleanup remains hardened/failure-visible',has(hard,'cleanup_upload_sessions','gdo_upload_cleanup_unsafe_path'))
c(75,'Canonical File20 shell integration remains adapter-only',has(integ,'gdo.file09.owner-contract','sabri_shell_page_contracts'))
c(76,'Files03/07/08/21/23/26 consume public-safe verification projections',has(integ,'gdo.file03.doctor-profile-eligibility','gdo.file07.directory-eligibility','gdo.file08.clinic-eligibility','gdo.file21.publishing-eligibility','gdo.file23.publishing-dashboard-eligibility','gdo.file26.doctor-verification-projection'))
c(77,'File26 excludes private evidence/donor ranking advantage',has(integ,"'evidence_exposed'","'donor_rank_advantage'","'private_indexing' => false"))
c(78,'All FR/NFR/Advanced-Trust IDs remain traceable',all(f'F09-FR-{i:03d}' in trace for i in range(1,18)) and all(f'F09-NFR-{i:03d}' in trace for i in range(1,11)) and all(f'F09-AT-{i:02d}' in trace for i in range(1,25)))
c(79,'Nine prior 80-round ledgers remain preserved as historical evidence',all((root/x).exists() for x in ['REVIEW-80-ROUNDS-RC6.md','REVIEW-80-ROUNDS-RC6-R2.md','REVIEW-80-ROUNDS-RC6-R3.md','REVIEW-80-ROUNDS-RC6-R4.md','REVIEW-80-ROUNDS-RC6-R5.md','REVIEW-80-ROUNDS-RC6-R6.md','REVIEW-80-ROUNDS-RC6-R7.md','REVIEW-80-ROUNDS-RC6-R8.md','REVIEW-80-ROUNDS-RC6-R9.md']))
c(80,'Tenth fresh ledger/gate/release-lock/61-entry package truth are synchronized',(root/'REVIEW-80-ROUNDS-RC6-R10.md').exists() and lock.get('tenth_review_baseline')=='ec3ca2dd715e05b66cf29c42f2f996c80987fcd7' and lock.get('tenth_review_rounds')==80 and lock.get('tenth_defect_rounds')==19 and lock.get('tenth_clean_rounds')==61 and lock.get('release_file_count')==len(release_files)==61 and 'tests/eighty-round-audit-r10.py' in workflow and '61-entry' in manifest and 'Tenth fresh 80-round' in status and 'Tenth fresh 80-round' in readme)
failed=[x for x in checks if not x[2]]
for n,topic,ok in checks: print(f'R{n:02d}: {"PASS" if ok else "FAIL"} — {topic}')
print(f'File 09 RC6 tenth fresh eighty-round audit: {len(checks)-len(failed)} PASS, {len(failed)} FAIL')
defects=set(range(4,23))
print('Defect-bearing rounds: ' + ','.join(f'{i:02d}' for i in sorted(defects)))
print('Clean rounds: ' + ','.join(f'{i:02d}' for i in range(1,81) if i not in defects))
if len(checks)!=80 or failed: raise SystemExit(1)
