<?php
defined('ABSPATH')||exit;
final class GDO_Admin{
	public function hooks(){add_action('admin_menu',array($this,'menu'));add_action('admin_post_gdo_review',array($this,'review'));add_action('admin_post_gdo_download',array($this,'download'));add_action('admin_notices',array($this,'notice'));}
	public function menu(){add_menu_page('Global Doctor Verification','Doctor Applications','manage_global_doctor_verification','global-doctor-verification',array($this,'page'),'dashicons-shield-alt',27);}
	public function page(){$users=get_users(array('role__in'=>array('sabri_doctor_pending','sabri_doctor_verified'),'number'=>250,'orderby'=>'registered','order'=>'DESC'));?><div class="wrap gdo-admin"><h1>Global Doctor Verification</h1><p>Review identity and professional evidence manually. Never approve a profile solely because documents were uploaded.</p><table class="widefat striped"><thead><tr><th>Applicant</th><th>Profile</th><th>Encrypted evidence</th><th>Review</th></tr></thead><tbody><?php if($users):foreach($users as $u):$docs=GDO_Helpers::documents($u->ID);?><tr><td><strong><?php echo esc_html($u->display_name);?></strong><br><?php echo esc_html($u->user_email);?><br><?php echo esc_html(SPD_Helpers::get($u->ID,'country'));?></td><td><?php echo absint(GDO_Helpers::completion($u->ID));?>% complete<br><?php echo esc_html(SPD_Helpers::get($u->ID,'qualification'));?><br>License: <?php echo esc_html(SPD_Helpers::get($u->ID,'licence_number'));?><br>Authority: <?php echo esc_html(SPD_Helpers::get($u->ID,'licensing_authority'));?></td><td><?php if($docs):foreach($docs as $doc):?><a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=gdo_download&document_id='.$doc->id),'gdo_download_'.$doc->id));?>"><?php echo esc_html(GDO_Helpers::types()[$doc->document_type]);?></a><br><small><?php echo esc_html($doc->mime_type);?> · <?php echo size_format($doc->file_size);?></small><br><?php endforeach;else:?>No documents<?php endif;?></td><td><form action="<?php echo esc_url(admin_url('admin-post.php'));?>" method="post"><input type="hidden" name="action" value="gdo_review"><input type="hidden" name="user_id" value="<?php echo absint($u->ID);?>"><?php wp_nonce_field('gdo_review_'.$u->ID);?><select name="status"><?php foreach(array('under_review','verified','more_info','rejected','suspended') as $s):?><option value="<?php echo esc_attr($s);?>" <?php selected(GDO_Helpers::status($u->ID),$s);?>><?php echo esc_html(SPD_Helpers::status_label($s));?></option><?php endforeach;?></select><textarea name="note" required placeholder="Internal review reason"></textarea><button class="button button-primary">Save Review</button></form></td></tr><?php endforeach;else:?><tr><td colspan="4">No doctor applications found.</td></tr><?php endif;?></tbody></table></div><?php }
	public function review(){$this->guard();$id=isset($_POST['user_id'])?absint($_POST['user_id']):0;check_admin_referer('gdo_review_'.$id);$new=isset($_POST['status'])?sanitize_key(wp_unslash($_POST['status'])):'';$note=isset($_POST['note'])?sanitize_textarea_field(wp_unslash($_POST['note'])):'';if(!get_userdata($id)||!in_array($new,array('under_review','verified','more_info','rejected','suspended'),true)||!trim($note)){wp_die(esc_html__('Invalid review.','global-doctor-onboarding'),'',array('response'=>400));}if('verified'===$new&&GDO_Helpers::completion($id)<100){wp_die(esc_html__('A doctor cannot be verified until the application is 100 percent complete.','global-doctor-onboarding'),'',array('response'=>400));}$old=GDO_Helpers::status($id);update_user_meta($id,'_spd_verification_status',$new);update_user_meta($id,'_gdo_reviewed_at',current_time('mysql',true));update_user_meta($id,'_gdo_reviewer_id',get_current_user_id());$u=new WP_User($id);$u->remove_role('sabri_doctor_pending');$u->remove_role('sabri_doctor_verified');$u->add_role('verified'===$new?'sabri_doctor_verified':'sabri_doctor_pending');SPD_Helpers::audit($id,$old,$new,$note);$user=get_userdata($id);if($user){wp_mail($user->user_email,'Doctor Verification Update','Your application status is now: '.SPD_Helpers::status_label($new).'. Log in to review your profile or requested changes.');}wp_safe_redirect(add_query_arg(array('page'=>'global-doctor-verification','updated'=>'1'),admin_url('admin.php')));exit;}
	public function download(){$this->guard();$id=isset($_GET['document_id'])?absint($_GET['document_id']):0;check_admin_referer('gdo_download_'.$id);global $wpdb;$doc=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}gdo_documents WHERE id=%d",$id));if(!$doc){wp_die(esc_html__('Document not found.','global-doctor-onboarding'),'',array('response'=>404));}$path=trailingslashit(GDO_Helpers::storage()).basename($doc->storage_name);$bytes=is_file($path)?GDO_Helpers::decrypt(file_get_contents($path)):false;if(false===$bytes){wp_die(esc_html__('The encrypted document could not be opened.','global-doctor-onboarding'),'',array('response'=>500));}nocache_headers();header('Content-Type: '.$doc->mime_type);header('Content-Disposition: attachment; filename="'.sanitize_file_name($doc->original_name).'"');header('Content-Length: '.strlen($bytes));echo $bytes;exit;}
	private function guard(){if(!current_user_can('manage_global_doctor_verification')){wp_die(esc_html__('Access denied.','global-doctor-onboarding'),'',array('response'=>403));}}
	public function notice(){if(current_user_can('activate_plugins')&&get_transient('gdo_notice')){delete_transient('gdo_notice');echo '<div class="notice notice-success is-dismissible"><p>Global Doctor Onboarding is active. Review Doctor Applications.</p></div>';}}
}

