<?php
defined( 'ABSPATH' ) || exit;

final class GDO_Frontend {
    public function hooks(){add_shortcode('gdo_doctor_application',array($this,'form'));add_action('admin_post_gdo_save_application',array($this,'save'));add_action('admin_post_gdo_submit_application',array($this,'submit'));add_action('admin_post_gdo_file_appeal',array($this,'appeal'));}
    public function form(){
        if(!is_user_logged_in())return '<div class="gdo-notice"><h2>'.esc_html__('Log in','global-doctor-onboarding').'</h2><p>'.esc_html__('A File 00-approved doctor account is required.','global-doctor-onboarding').'</p></div>';
        $user=get_current_user_id(); if(!GDO_Membership_Adapter::is_active_doctor_candidate($user))return '<div class="gdo-notice">'.esc_html__('File 00 has not approved this account for doctor onboarding.','global-doctor-onboarding').'</div>';
        $app=GDO_Application::ensure_draft($user); if(is_wp_error($app)){$latest=GDO_Application::latest_for_user($user);return '<div class="gdo-notice"><h2>'.esc_html__('Application status','global-doctor-onboarding').'</h2><p>'.esc_html($latest?$latest->state:$app->get_error_message()).'</p></div>';}
        $profile=json_decode($app->profile_json,true); if(!is_array($profile))$profile=array_fill_keys(GDO_Application::fields(),''); $consent=GDO_Application::consent_text();
        ob_start();?><main class="gdo-shell"><header class="gdo-head"><span><?php esc_html_e('Private professional application','global-doctor-onboarding');?></span><h1><?php esc_html_e('Doctor Application and Verification','global-doctor-onboarding');?></h1><p><?php esc_html_e('Credential files remain private and are reviewed independently. Verification does not guarantee treatment outcomes.','global-doctor-onboarding');?></p></header><section class="gdo-progress"><strong><?php echo esc_html($app->state);?></strong><p><?php printf(esc_html__('Application version %d','global-doctor-onboarding'),absint($app->version));?></p></section>
        <form class="gdo-form" action="<?php echo esc_url(admin_url('admin-post.php'));?>" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="gdo_save_application"><input type="hidden" name="application_id" value="<?php echo absint($app->id);?>"><input type="hidden" name="row_version" value="<?php echo absint($app->row_version);?>"><?php wp_nonce_field('gdo_save_application_'.$app->id);?>
        <?php foreach(array('display_name'=>'Full professional name','country'=>'Country','city'=>'City','clinic'=>'Clinic or professional address','qualification'=>'Primary qualification','license_number'=>'License or registration number','licensing_authority'=>'Licensing authority','experience_years'=>'Years of professional experience','specialty'=>'Professional specialty','languages'=>'Languages','consultation_modes'=>'Consultation methods','phone'=>'Phone number','whatsapp'=>'WhatsApp number') as $key=>$label):?><label><?php echo esc_html($label);?><input name="<?php echo esc_attr($key);?>" required value="<?php echo esc_attr($profile[$key]??'');?>"></label><?php endforeach;?><label class="gdo-wide"><?php esc_html_e('Professional biography','global-doctor-onboarding');?><textarea name="bio" required><?php echo esc_textarea($profile['bio']??'');?></textarea></label>
        <?php foreach(GDO_Evidence::types() as $key=>$label):$current=GDO_Evidence::current($app->id,$key);?><label class="gdo-file"><?php echo esc_html($label);?><?php if($current):?><small><?php echo esc_html(sprintf(__('Current evidence version %d — %s','global-doctor-onboarding'),$current->version,$current->status));?></small><?php else:?><small><?php esc_html_e('Required. PDF, JPEG, PNG, or WebP; maximum 5 MB.','global-doctor-onboarding');?></small><?php endif;?><input type="file" name="document_<?php echo esc_attr($key);?>" accept="application/pdf,image/jpeg,image/png,image/webp" <?php echo $current?'':'required';?>></label><?php endforeach;?>
        <div class="gdo-wide gdo-consent"><p><?php echo esc_html($consent['wording']);?></p><p><strong><?php esc_html_e('Purpose:','global-doctor-onboarding');?></strong> <?php echo esc_html($consent['purpose']);?></p><p><strong><?php esc_html_e('Retention:','global-doctor-onboarding');?></strong> <?php echo esc_html($consent['retention']);?></p><label><input type="checkbox" name="consent" value="1" required> <?php printf(esc_html__('I accept consent version %s.','global-doctor-onboarding'),esc_html($consent['version']));?></label></div><button class="gdo-button" type="submit"><?php esc_html_e('Save private application','global-doctor-onboarding');?></button></form>
        <form action="<?php echo esc_url(admin_url('admin-post.php'));?>" method="post"><input type="hidden" name="action" value="gdo_submit_application"><input type="hidden" name="application_id" value="<?php echo absint($app->id);?>"><input type="hidden" name="row_version" value="<?php echo absint($app->row_version);?>"><?php wp_nonce_field('gdo_submit_application_'.$app->id);?><button class="gdo-button" type="submit"><?php esc_html_e('Submit for independent review','global-doctor-onboarding');?></button></form></main><?php return ob_get_clean();
    }
    public function save(){if(!is_user_logged_in())wp_die(esc_html__('Log in.','global-doctor-onboarding'),'',array('response'=>403));$id=absint($_POST['application_id']??0);check_admin_referer('gdo_save_application_'.$id);$user=get_current_user_id();$app=GDO_Application::get($id);if(!$app||absint($app->user_id)!==$user)wp_die(esc_html__('Application access denied.','global-doctor-onboarding'),'',array('response'=>403));$profile=GDO_Application::sanitize_profile($_POST);$valid=GDO_Application::validate_profile($profile);if(is_wp_error($valid))wp_die(esc_html($valid->get_error_message()),'',array('response'=>400));global $wpdb;$wpdb->query('START TRANSACTION');$new_files=array();try{$saved=GDO_Application::save_draft($id,$user,$profile,absint($_POST['row_version']??0));if(is_wp_error($saved))throw new RuntimeException($saved->get_error_message());$app=GDO_Application::get($id);foreach(GDO_Evidence::types() as $type=>$label){$key='document_'.$type;if(!empty($_FILES[$key]['tmp_name'])){$record=GDO_Evidence::stage_upload($app,$type,$_FILES[$key]);if(is_wp_error($record))throw new RuntimeException($record->get_error_message());$new_files[]=$record;}}$consent=GDO_Application::record_consent($id,$user,!empty($_POST['consent']));if(is_wp_error($consent))throw new RuntimeException($consent->get_error_message());$wpdb->query('COMMIT');}catch(Throwable $e){$wpdb->query('ROLLBACK');foreach($new_files as $created){if(is_array($created)&&!empty($created['storage_name']))GDO_Storage::delete_verified($created['storage_name'],$created['ciphertext_sha256']??'');}wp_die(esc_html($e->getMessage()),'',array('response'=>400));}wp_safe_redirect(GDO_Plugin::application_url(array('saved'=>1)));exit;}
    public function submit(){if(!is_user_logged_in())wp_die(esc_html__('Log in.','global-doctor-onboarding'),'',array('response'=>403));$id=absint($_POST['application_id']??0);check_admin_referer('gdo_submit_application_'.$id);$result=GDO_Application::submit($id,get_current_user_id(),absint($_POST['row_version']??0));if(is_wp_error($result))wp_die(esc_html($result->get_error_message()),'',array('response'=>400));wp_safe_redirect(GDO_Plugin::application_url(array('submitted'=>1)));exit;}
    public function appeal(){if(!is_user_logged_in())wp_die(esc_html__('Log in.','global-doctor-onboarding'),'',array('response'=>403));$id=absint($_POST['application_id']??0);check_admin_referer('gdo_file_appeal_'.$id);$app=GDO_Application::get($id);$reason=sanitize_textarea_field($_POST['reason']??'');if(!$app||absint($app->user_id)!==get_current_user_id()||!in_array($app->state,array('rejected','suspended'),true)||strlen($reason)<20)wp_die(esc_html__('The appeal is invalid.','global-doctor-onboarding'),'',array('response'=>400));global $wpdb;$wpdb->insert(GDO_Schema::table('appeals'),array('application_id'=>$id,'user_id'=>$app->user_id,'status'=>'open','reason'=>$reason,'created_at'=>current_time('mysql',true)),array('%d','%d','%s','%s','%s'));$result=GDO_State::transition($id,'appeal_pending',$app->user_id,'applicant_appeal',$reason,$app->row_version);if(is_wp_error($result))wp_die(esc_html($result->get_error_message()),'',array('response'=>409));GDO_Notifications::queue('doctor_verification_appeal',$app->user_id,array('application_id'=>$id));wp_safe_redirect(GDO_Plugin::application_url(array('appealed'=>1)));exit;}
}
