<?php
defined('ABSPATH')||exit;
final class GDO_Privacy{
	public function hooks(){add_filter('wp_privacy_personal_data_exporters',array($this,'exporters'));add_filter('wp_privacy_personal_data_erasers',array($this,'erasers'));add_action('admin_init',array($this,'policy'));}
	public function exporters($e){$e['global-doctor-onboarding']=array('exporter_friendly_name'=>'Global Doctor Application','callback'=>array($this,'export'));return $e;}
	public function export($email,$page=1){$u=get_user_by('email',$email);if(!$u){return array('data'=>array(),'done'=>true);}$rows=array(array('name'=>'Application status','value'=>SPD_Helpers::status_label(GDO_Helpers::status($u->ID))),array('name'=>'Submitted at','value'=>get_user_meta($u->ID,'_gdo_submitted_at',true)),array('name'=>'Reviewed at','value'=>get_user_meta($u->ID,'_gdo_reviewed_at',true)));foreach(GDO_Helpers::documents($u->ID) as $doc){$rows[]=array('name'=>'Credential document','value'=>GDO_Helpers::types()[$doc->document_type].' — '.$doc->original_name.' — '.$doc->uploaded_at.' UTC');}return array('data'=>array(array('group_id'=>'global-doctor-application','group_label'=>'Global Doctor Application','item_id'=>'application-'.$u->ID,'data'=>$rows)),'done'=>true);}
	public function erasers($e){$e['global-doctor-onboarding']=array('eraser_friendly_name'=>'Global Doctor Application','callback'=>array($this,'erase'));return $e;}
	public function erase($email,$page=1){$u=get_user_by('email',$email);if(!$u){return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);}global $wpdb;$docs=GDO_Helpers::documents($u->ID);foreach($docs as $doc){$path=trailingslashit(GDO_Helpers::storage()).basename($doc->storage_name);if(is_file($path)){unlink($path);}}$wpdb->delete($wpdb->prefix.'gdo_documents',array('user_id'=>$u->ID),array('%d'));update_user_meta($u->ID,'_spd_verification_status','rejected');delete_user_meta($u->ID,'_gdo_submitted_at');delete_user_meta($u->ID,'_gdo_reviewer_id');return array('items_removed'=>true,'items_retained'=>true,'messages'=>array('Credential files were deleted. Minimal verification audit history may be retained for security accountability.'),'done'=>true);}
	public function policy(){if(function_exists('wp_add_privacy_policy_content')){wp_add_privacy_policy_content('Global Doctor Verification','<p class="privacy-policy-tutorial">Doctor applicants provide professional profile information and encrypted identity, qualification, and licensing evidence for manual verification. Credential files are encrypted at rest and available only to authorized verification administrators. Public listing begins only after approval.</p>');}}
}

