from pathlib import Path
root=Path.cwd()
def r(p): return (root/p).read_text(encoding='utf-8')
def w(p,s): (root/p).write_text(s,encoding='utf-8')
def rep(p,a,b,n=1):
 s=r(p)
 if s.count(a)<n: raise SystemExit(f'{p}: missing expected text: {a[:120]!r}')
 w(p,s.replace(a,b,n)); print('patched',p)
p='includes/class-gdo-admin.php'
rep(p,"\t\tif ( 'verified' === $decision && ( ! GDO_Evidence::all_accepted( $id ) || ! $until || strtotime( $until . ' 23:59:59 UTC' ) <= time() || GDO_Risk::unresolved( $id, 'high' ) ) ) {","\t\tif ( 'verified' === $decision && ( ! GDO_Evidence::all_accepted( $id ) || ! $until || strtotime( $until . ' 23:59:59 UTC' ) <= time() || GDO_Risk::unresolved( $id, 'high' ) || ! GDO_Membership_Adapter::is_active_doctor_candidate( $app->user_id ) ) ) {")
rep(p,"'schema'=>6,","'schema'=>GDO_SCHEMA_VERSION,",1)
rep(p,"\t\tif ( 'reinstated' === $state && ( ! GDO_Evidence::all_accepted( $id ) || ! $until || strtotime( $until . ' 23:59:59 UTC' ) <= time() ) ) {\n\t\t\twp_die( esc_html__( 'Reinstatement requires accepted current evidence and a future validity date.', 'global-doctor-onboarding' ), '', array( 'response'=>400 ) );\n\t\t}\n\t\t$wpdb->query( 'START TRANSACTION' );","\t\t$snapshot_refresh = array();\n\t\tif ( 'reinstated' === $state && ( ! GDO_Evidence::all_accepted( $id ) || ! $until || strtotime( $until . ' 23:59:59 UTC' ) <= time() || GDO_Risk::unresolved( $id, 'high' ) || ! GDO_Membership_Adapter::is_active_doctor_candidate( $app->user_id ) ) ) {\n\t\t\twp_die( esc_html__( 'Reinstatement requires current File 00 assurance, accepted evidence, a future validity date, and resolved high-risk signals.', 'global-doctor-onboarding' ), '', array( 'response'=>400 ) );\n\t\t}\n\t\tif ( 'reinstated' === $state ) {\n\t\t\t$snapshot_refresh = GDO_Application::refresh_approved_snapshot( $app, $until, $actor );\n\t\t\tif ( is_wp_error( $snapshot_refresh ) ) { wp_die( esc_html( $snapshot_refresh->get_error_message() ), '', array( 'response'=>409 ) ); }\n\t\t}\n\t\t$wpdb->query( 'START TRANSACTION' );")
rep(p,"\t\tif ( 'reinstated' === $state ) { $data['verified_until'] = gmdate( 'Y-m-d 23:59:59', strtotime( $until . ' UTC' ) ); $data['finalizer_id'] = $actor; $formats[]='%s'; $formats[]='%d'; }","\t\tif ( 'reinstated' === $state ) { $data['verified_until'] = $snapshot_refresh['verified_until']; $data['finalizer_id'] = $actor; $data['approved_snapshot_json'] = $snapshot_refresh['json']; $data['approved_fingerprint'] = $snapshot_refresh['fingerprint']; $formats[]='%s'; $formats[]='%d'; $formats[]='%s'; $formats[]='%s'; }")
rep(p,"GDO_Claims::issue( $id, $state, array(), false );","GDO_Claims::issue( $id, $state, 'reinstated' === $state ? $snapshot_refresh['snapshot'] : array(), false );",1)
rep(p,"do_action( 'gdo_verification_decision_changed', $app->user_id, $state, $id, array() );","do_action( 'gdo_verification_decision_changed', $app->user_id, $state, $id, 'reinstated' === $state ? $snapshot_refresh['snapshot'] : array() );",1)
rep(p,"\t\tif ( 'reinstated' === $decision && ( ! GDO_Evidence::all_accepted( $id ) || ! $until || strtotime( $until . ' 23:59:59 UTC' ) <= time() ) ) {\n\t\t\twp_die( esc_html__( 'Reinstatement requires current accepted evidence and a future validity date.', 'global-doctor-onboarding' ), '', array( 'response'=>400 ) );\n\t\t}\n\t\t$wpdb->query( 'START TRANSACTION' );","\t\t$snapshot_refresh = array();\n\t\tif ( 'reinstated' === $decision && ( ! GDO_Evidence::all_accepted( $id ) || ! $until || strtotime( $until . ' 23:59:59 UTC' ) <= time() || GDO_Risk::unresolved( $id, 'high' ) || ! GDO_Membership_Adapter::is_active_doctor_candidate( $app->user_id ) ) ) {\n\t\t\twp_die( esc_html__( 'Reinstatement requires current File 00 assurance, accepted evidence, a future validity date, and resolved high-risk signals.', 'global-doctor-onboarding' ), '', array( 'response'=>400 ) );\n\t\t}\n\t\tif ( 'reinstated' === $decision ) {\n\t\t\t$snapshot_refresh = GDO_Application::refresh_approved_snapshot( $app, $until, $actor );\n\t\t\tif ( is_wp_error( $snapshot_refresh ) ) { wp_die( esc_html( $snapshot_refresh->get_error_message() ), '', array( 'response'=>409 ) ); }\n\t\t}\n\t\t$wpdb->query( 'START TRANSACTION' );")
rep(p,"\t\tif ( 'reinstated' === $decision ) { $app_data['verified_until']=gmdate( 'Y-m-d 23:59:59', strtotime( $until . ' UTC' ) ); $app_data['finalizer_id']=$actor; $formats[]='%s'; $formats[]='%d'; }","\t\tif ( 'reinstated' === $decision ) { $app_data['verified_until']=$snapshot_refresh['verified_until']; $app_data['finalizer_id']=$actor; $app_data['approved_snapshot_json']=$snapshot_refresh['json']; $app_data['approved_fingerprint']=$snapshot_refresh['fingerprint']; $formats[]='%s'; $formats[]='%d'; $formats[]='%s'; $formats[]='%s'; }")
rep(p,"GDO_Claims::issue( $id, $decision, array(), false );","GDO_Claims::issue( $id, $decision, 'reinstated' === $decision ? $snapshot_refresh['snapshot'] : array(), false );",1)
print('admin lifecycle patch complete')
